### ISSUE TITLE
recenter.py

### ISSUE THREAD

**Issue by Rafael-Ayala** [asarnow/pyem#1]
Hi,

I recently found this repository and the functionality provided by recenter.py looked very interesting. I was wondering if there is an updated finished version? 

Best wishes,

Rafa

**Comment by asarnow** [comment]
Hi Rafael, thanks for your interest!

I apologize for the slow reply - I was traveling to the Biophysical Society Meeting last week.

Right now there are three recentering methods planned or present in my code:

* recenter on the transformed center of mass of a 3D density (change originX and originY)
* recenter on the center of mass of a corresponding 2D class (change originX and originY)
* recenter in the raw micrographs for re-extraction (fix coordinateX and coordinateY and zero originX and originY)

The first one is implemented but not in recenter.py yet, the second one is not implemented, and the third one is possible using star.py to generate new coordinate files for Relion.

Given your interest, I'll get all three methods into recenter.py in the next couple days. After I push the changes, any help you could give with testing would be very appreciated.

**Comment by Rafael-Ayala** [comment]
Hi Daniel,

Sorry for such a late reply! I just realized your repply!

Thanks a lot, that would be quite interesting to try as I have a dataset where the domain of interests is quite peripheral and I would like to recenter it after density subtraction and 2D classification!

Best wishes,

Rafael

**Comment by domgutier** [comment]
Hello, 

I was wondering how you recenter with your cryosparc output. The star file I get does not have originX and originY values. 

Best,
Dominique

**Comment by asarnow** [comment]
This isn't related to this issue, which is about recentering methods for particle images.

I'm sure you mean that your file doesn't have the rlnCoordinateX/Y values, rather than rlnOriginX/Y. It's covered in the [wiki](https://github.com/asarnow/pyem/wiki/Export-particles-from-cryoSPARC).

**Comment by asarnow** [comment]
@domgutier My apologies, I forgot about an issue with *2D classification* output from cryosparc. The particle shift parameters are *not* present in the metadata, so there's nothing to convert. You can still re-extract the particles from the chosen classes, by *not* recentering when extracting refined particles (in Relion, set "recenter particles" to "no").

**Comment by petervanblerkom** [comment]
Hello Rafael,

I've run into a few issues in an attempt to run the recenter.py program to recenter particles in a particles.star file using 2d class averages. Perhaps it is now outdated?

First, it seems that I needed to change the code in a couple places to get it to try to run:

`from star import parse_star, write_star` (line 24)
to
`from pyem.star import parse_star, write_star`

as well as:

`for ptcl in star.rows:` (line 51 & 57)
to
`for ptcl in star.iterrows()`

But now I'm stuck at the error

`NameError: global name 'meta' is not defined`

Which seems to have to do with transform_com in line 77 and 79.

Any help on this issue would be most welcome.

Thank you,

-Peter

**Comment by asarnow** [comment]
`recenter.py` has never really been more than a collection of unfinished ideas about automatically centering particles based on image features. I've considered deleting it from the main branch several times.

Just updating the particle coordinates based on the shifts can be done using `star.py` or during extraction in Relion-2+ itself. You can also center the particles on an arbitrary location in the 3D volume using `subparticles.py` or again in Relion-3.

What do you actually want to do? If you want to e.g. center the particles based on the center-of-mass of the assigned 2D/3D class we can get this feature working, it just hasn't been a priority for me given the approaches mentioned above.

**Comment by petervanblerkom** [comment]
Thank you for the quick response Daniel!

I'm sure there's other ways to go about what I'm attempting, and I'll look more into what you've mentioned, but I thought that recentering the particles based on the 2D class would be an easy way forward for what I'm trying to do.

However, I do think I've figured out some modifications to the code that have resulted in possibly convincing results if I understood what it's supposed to be doing correctly. Still waiting on the 2d averages to find out if it actually helped in the way I wanted it to.

If you're curious, here's the modified code that appears to be working (for 2d averages at least, haven't tried 3d)


    import glob
    import logging
    import sys
    import numpy as np
    import pandas as pd
    from pyem.star import parse_star, write_star
    from EMAN2 import EMData, Vec2f, Vec3f, Transform


    def main(args):
        star = parse_star(args.input, keep_index=False)

        if args.class_2d is not None:
            refs = glob.glob(args.class_2d)
        elif args.class_3d is not None:
            refs = glob.glob(args.class_3d)
        else:
            refs = []
    
        shifts = []
        for r in refs:
            if args.class_3d is not None:
                refmap = EMData(r)
                com = Vec3f(*refmap.phase_cog()[:3])
                shifts.append(com)
            else:
                stack = EMData.read_images(r)
                for im in stack:
                    com = Vec2f(*im.phase_cog()[:2])
                    shifts.append(com)


        if args.class_2d is None and args.class_3d is None:
            for index, ptcl in star.iterrows():
                im = EMData.read_image(ptcl)
                com = im.phase_cog()
                star.loc[index,"rlnOriginX"] += com[0]
                star.loc[index,"rlnOriginY"] += com[1]
	 		
        else:
            for index, ptcl in star.iterrows():
                com = shifts[ptcl["rlnClassNumber"]-1]
                xshift, yshift = transform_com(com, ptcl)
                star.loc[index,'rlnOriginX'] += xshift
                star.loc[index,'rlnOriginY'] += yshift

        if args.zero_origin:
            star["rlnCoordinateX"] = star["rlnCoordinateX"] - star["rlnOriginX"]
            star["rlnCoordinateY"] = star["rlnCoordinateY"] - star["rlnOriginY"]
            star["rlnOriginX"] = 0
            star["rlnOriginY"] = 0

        write_star(args.output, star, reindex=True)

        return 0


    def transform_com(com, ptcl):
        t = Transform()
        if len(com) == 3:
            t.set_rotation({'psi': ptcl["rlnAnglePsi"], 'phi': ptcl["rlnAngleRot"], 'theta': ptcl["rlnAngleTilt"], 'type': 'spider'})
        else:
            t.set_rotation({'type': 'spider', 'psi': ptcl["rlnAnglePsi"]})
        shift = t.transform(com)
        # The change in the origin is the projection of the transformed difference vector on the new xy plane.
        return shift[0], shift[1]


    def find_cm(im):
        l = np.floor(im.shape[0] / 2)
        x, y = np.meshgrid(np.arange(-l, l, dtype=np.double), np.arange(-l, l, dtype=np.double))
        mu_x = np.average(x, axis=None, weights=im)
        mu_y = np.average(y, axis=None, weights=im)
        return mu_x, mu_y


    if __name__ == "__main__":
        import argparse
        parser = argparse.ArgumentParser()
        parser.add_argument("--class-2d", help="2D class images for recentering (pass glob in quotes for multiple files)")
        parser.add_argument("--class-3d", help="3D class images for recentering (pass glob in quotes for multiple files)")
        parser.add_argument("--zero-origin", help="Subtract particle origin from particle coordinates in output")
        parser.add_argument("input", help="Input .star file")
        parser.add_argument("output", help="Output .star file")
        args = parser.parse_args()
        #logger = logging.getLogger(__name__)
        #logger.setLevel(logging.getLevelName(args.loglevel.upper()))
        sys.exit(main(args))`

**Comment by asarnow** [comment]
I don't see a need for any of the features I had planned for recenter.py, so I'm closing this. I may delete recenter.py from the master branch.
