### ISSUE TITLE
csparc2star.py to be used for movie refinement

### ISSUE THREAD

**Issue by aglape** [asarnow/pyem#10]
Hello,

we succesfully use csparc2star.py to carry out refinement in relion, but when we try to re-extract the data to then do a movie refinement it doesn't work.
Do you know how we could that?
Classification in relion takes forever and we use cryosparc for everything but the movie refinement only works in relion. We are trying to squeeze as much from the data as possible.
Thanks for any advice you can give me.
Best,
Chiara

**Comment by asarnow** [comment]
The micrograph path and particle coordinates are not saved by cryoSPARC. Please check out this [tutorial](https://github.com/asarnow/pyem/wiki/Export-particles-from-cryoSPARC) for re-extracting particles after refinement in cryoSPARC.

Feel free to re-open the issue if you have problems following the instructions in the wiki.

**Comment by aglape** [comment]
That worked. Thanks!

Chiara Rapisarda
aglape@gmail.com
