### ISSUE TITLE
Converting exported `.cs` file includes`>` char in file paths

### ISSUE THREAD

**Issue by arulths** [asarnow/pyem#102]
This issue was originally brought up here: https://github.com/asarnow/pyem/issues/50

When a CryoSPARC job or CryoSPARC result group is "[exported](https://guide.cryosparc.com/setup-configuration-and-management/software-system-guides/tutorial-data-management-in-cryosparc#5.-ability-to-export-and-import-individual-jobs)", all of a particle's result fields are merged together into a single `.cs` file. This makes it easy for users to move these jobs or result groups around without also having to worry about a `passthrough.cs` file. When the export action is used, **all paths in the .cs file are prepended with the "`>`" character** to internally indicate that the data referenced by the `.cs` file is located adjacent to itself (as opposed to non-exported `.cs` files, where the data is relative to the project directory).  This character is removed from each path when the job or result group is imported back into a CryoSPARC instance.

Using `csparc2star.py` on an exported .cs file includes the "`>`" character, so users have to run a separate command on the .star file to remove it before using it downstream: [see the CryoSPARC discussion forum post.](https://discuss.cryosparc.com/t/csparc2star-output-relion-compatibility/4978/14?u=stephan)

This character can be safely removed, since it's only used internally by CryoSPARC.

I'm hoping to make a PR to fix this soon, but posting here for bookkeeping.

**Comment by asarnow** [comment]
Great, thanks! I think the right place to put it is towards the end of `metadata.cryosparc2.parse_cryosparc_2_cs()`. Then do something like `for field in [star.Relion.FOOPATH, star.Relion.BAZPATH]: if field in df: ...` etc.
