### ISSUE TITLE
star.file format error using pyem

### ISSUE THREAD

**Issue by mqcarba** [asarnow/pyem#103]
Hi I have an issue in the .star file format after creating using pyem. I'm not able to run 2D class in Relion 4.0. I got this answer from Takanori in the Relion forum:

_[biochem-fan](https://github.com/biochem-fan) commented [1 hour ago](https://github.com/3dem/relion/issues/849#issuecomment-1518894088)
**_The column name rlnOpticsGroup1 does not make sense._**
Please ask to pyem developers. This is not RELION's problem but theirs._

My star file is:

data_optics

loop_
_rlnVoltage https://github.com/3dem/relion/issues/1
_rlnImagePixelSize https://github.com/3dem/relion/issues/2
_rlnSphericalAberration https://github.com/3dem/relion/issues/3
_rlnAmplitudeContrast https://github.com/3dem/relion/issues/4
_rlnOpticsGroup https://github.com/3dem/relion/issues/5
_rlnImageSize https://github.com/3dem/relion/issues/6
_rlnImageDimensionality https://github.com/3dem/relion/issues/7
_rlnOpticsGroup1 https://github.com/3dem/relion/issues/8
200.000000 1.100000 2.700000 0.100000 6 256 2 6

data_particles

loop_
_rlnImageName https://github.com/3dem/relion/issues/1
_rlnMicrographName https://github.com/3dem/relion/issues/2
_rlnCoordinateX https://github.com/3dem/relion/issues/3
_rlnCoordinateY https://github.com/3dem/relion/issues/4
_rlnDefocusU https://github.com/3dem/relion/issues/5
_rlnDefocusV https://github.com/3dem/relion/issues/6
_rlnDefocusAngle https://github.com/3dem/relion/issues/7
_rlnPhaseShift https://github.com/3dem/relion/issues/8
_rlnCtfBfactor https://github.com/3dem/relion/issues/9
_rlnOpticsGroup1 https://github.com/3dem/relion/issues/10
000001@J220/extract/000032024661002688670_FoilHole_17705165_Data_17702841_17702843_20221217_092342_Fractions_patch_aligned_doseweighted_particles.mrcs J89/motioncorrected/000032024661002688670_FoilHole_17705165_Data_17702841_17702843_20221217_092342_Fractions_patch_aligned_doseweighted.mrc 3568 696 29705.314453 29126.382812 21.248625 0.000000 0.000000 6

**Comment by asarnow** [comment]
There's no condition in which a column label like _rlnOpticsGroup1 will be emitted - same for those extra strings after the field names. Have you modified the output file aside from the instructions in the wiki?

**Comment by asarnow** [comment]
That's not the file you showed Takanori. Anyway, just follow the instructions in the wiki here to correct the paths to the particle stacks, and it will work.
