### ISSUE TITLE
rlnOriginX and rlnOriginY values are missing!!!

### ISSUE THREAD

**Issue by fonsecareyna82** [asarnow/pyem#106]
When generate the .star file, this metadata values are missing. This means that when generating the transformation matrix of the particles, the shifts are lost. I don't know if pyem generate a wrong .star due the .cs files don't contains this values, or a pyem error.

**Comment by asarnow** [comment]
To clarify there is no warning for the shifts specifically but it should not happen that you have only shifts or only angles. (Even for 2D, there is an angle).

**Comment by fonsecareyna82** [comment]
Hi @asarnow, everything is now solved. I didn't realize that the new labels for relion are rlnOriginXAngst and rlnOriginYAngst. Sorry for the inconvenience. I was trying to create the transformation matrix by asking the .star for the values of  rlnOriginX and  rlnOriginY..
