### ISSUE TITLE
csparc2star.py   -  AttributeError: 'module' object has no attribute 'Relion'

### ISSUE THREAD

**Issue by pherepanov** [asarnow/pyem#11]
Dear Daniel, 

I did not have this issue with the previous versions of csparc2star.py. 
Am I missing something in my new pyem or Eman installation? 

pyem was installed with 
pip install git+https://github.com/asarnow/pyem

I am using python that comes with Eman2.2 

Thank you, 

Peter 

>./csparc2star.py cryosparc_exp000873_008.csv cryosparc_exp000873_008.star
Traceback (most recent call last):
  File "./csparc2star.py", line 171, in <module>
    sys.exit(main(parser.parse_args()))
  File "./csparc2star.py", line 108, in main
    if df.columns.intersection(star.Relion.ANGLES).size == len(star.Relion.ANGLES):
AttributeError: 'module' object has no attribute 'Relion'

**Comment by asarnow** [comment]
Hi Peter.

It sounds like the pyem library is out of date. When you update
csparc2star.py or the other command line programs, you should also update
the library installation as well. You can re-run the `pip install` command
to re-install from the current version on git (you may also need
`--upgrade`).

However, the easiest thing to do is to clone the git repository, and use
`pip install -e` to install using a link. Then, you can add the repo to
your PATH, or make symbolic links in your `$HOME/bin` or another location
on the PATH pointing to the command line programs. This way, you can just
do `git pull` in the repo and everything will be updated at once. This
method is shown in the wiki articles about installing pyem.

**Comment by pherepanov** [comment]
"--upgrade" did the trick; it all seems to work now. 
Thank you!! 
Peter

**Comment by asarnow** [comment]
@pherepanov Great. Don't hesitate to post any further questions!

**Comment by pherepanov** [comment]
Hi Daniel,

What reference should we use to cite pyem?

Thank you,

Peter

**Comment by pherepanov** [comment]
Hi Daniel,

Does the latest version of pyem work to convert cs back to the recent
version of relion star file?

I remember you announced that you will not be updating it anymore, but I
dont think the tools are available through cryosparc gui yet... It would be
really good to be able to import refined cs particle file to carry out
classification without realignment in relion.

Peter
Peter
