### ISSUE TITLE
KeyError:'rlnImageName'

### ISSUE THREAD

**Issue by Shian2011** [asarnow/pyem#110]
I just installed the latest version of Pyem as well as cryosparc (v4). When I convert .cs particles from a refinement job to .star file, it says KeyError: 'rlnImageName'. Can someone take a look at this below message and help me troubleshoot? Thanks a lot!

/home/XXX/pyem/csparc2star.py --copy-micrograph-coordinates particles.star particles.cs J508.star

Traceback (most recent call last):
  File "/home/XXX/.conda/envs/pyem/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rlnImageName'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/XXX/pyem/csparc2star.py", line 179, in <module>
    sys.exit(main(parser.parse_args()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/pyem/csparc2star.py", line 105, in main
    df = star.augment_star_ucsf(df, inplace=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/pyem/pyem/star.py", line 637, in augment_star_ucsf
    if "@" in df.iloc[0][Relion.IMAGE_NAME]:
              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.conda/envs/pyem/lib/python3.11/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.conda/envs/pyem/lib/python3.11/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.conda/envs/pyem/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'rlnImageName'

**Comment by asarnow** [comment]
Looks like you need to include the passthrough .cs file, like in the wiki tutorial.

**Comment by kdr400219** [comment]
@asarnow Just to chime in - I also experienced this issue after upgrading to the latest version of PyEM (I was previously using a PyEM before the whole change in NumPy int). In my case I don't think it's a passthrough issue - I've tried that, and also using exported particles, to no avail. To make sure I wasn't going totally insane, I retried a command that previously worked in the older version of PyEM (in the same format as @Shian2011 ), and got the same error. For reference, the original Relion .star file is from polishing, and I'm using coordinates from a round of NU-refinement. I am also using CS v4.3.1 and Relion 4.0. 

Let me know if I can provide any other info. Thanks in advance for your help (and your service to the community)!

**Comment by irinaelkhoury** [comment]
We have experienced the same issue with our install. Please advise:
Here is an error:
/home/scicons/cascade/apps/pyem-git/csparc2star.py J5_class_00_00262_particles.cs J5_passthrough_particles_class_0.cs J5_class_00_00262_particles.star --strip-uid --copy-micrograph-coordinates ../J1/particles.star --loglevel debug
Detected CryoSPARC 2+ .cs file
Reading primary file
Assigning pose from single 3D refinement
Reading auxiliary file J5_passthrough_particles_class_0.cs
Copying image size
Trying to merge: blob/path, blob/idx, blob/shape, blob/psize_A, blob/sign, blob/import_sig, ctf/type, ctf/exp_group_id, ctf/accel_kv, ctf/cs_mm, ctf/amp_contrast, ctf/df1_A, ctf/df2_A, ctf/df_angle_rad, ctf/phase_shift_rad, ctf/scale, ctf/scale_const, ctf/shift_A, ctf/tilt_A, ctf/trefoil_A, ctf/tetra_A, ctf/anisomag, ctf/bfactor, alignments2D/split, alignments2D/shift, alignments2D/pose, alignments2D/psize_A, alignments2D/error, alignments2D/error_min, alignments2D/resid_pow, alignments2D/slice_pow, alignments2D/image_pow, alignments2D/cross_cor, alignments2D/alpha, alignments2D/alpha_min, alignments2D/weight, alignments2D/pose_ess, alignments2D/shift_ess, alignments2D/class_posterior, alignments2D/class, alignments2D/class_ess, pick_stats/ncc_score, pick_stats/power, pick_stats/template_idx, pick_stats/angle_rad
Merging: ucsfImagePath, rlnImagePixelSize, rlnDefocusV, ucsfImageIndex, rlnPhaseShift, rlnDefocusAngle, rlnAmplitudeContrast, rlnSphericalAberration, rlnOpticsGroup, rlnVoltage, rlnCtfBfactor, rlnDefocusU, rlnImageSize
Directly copied fields: ucsfUid, rlnRandomSubset, rlnOriginX, rlnOriginY, rlnAngleRot, rlnAngleTilt, rlnAnglePsi, rlnClassNumber, ucsfImagePath, rlnImagePixelSize, rlnDefocusV, ucsfImageIndex, rlnPhaseShift, rlnDefocusAngle, rlnAmplitudeContrast, rlnSphericalAberration, rlnOpticsGroup, rlnVoltage, rlnCtfBfactor, rlnDefocusU, rlnImageSize
Converting DEFOCUSANGLE from radians to degrees
Converting PHASESHIFT from degrees to radians
Changing RANDOMSUBSET to 1-based index
Changing CLASS to 1-based index
Changing OPTICSGROUP to 1-based index
Converting Rodrigues coordinates to Euler angles
Converted Rodrigues coordinates to Euler angles
Traceback (most recent call last):
  File "/home/scicons/cascade/apps/python/3.6/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4411, in get_value
    return libindex.get_value_at(s, key)
  File "pandas/_libs/index.pyx", line 44, in pandas._libs.index.get_value_at
  File "pandas/_libs/index.pyx", line 45, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scicons/cascade/apps/pyem-git/csparc2star.py", line 181, in <module>
    sys.exit(main(parser.parse_args()))
  File "/home/scicons/cascade/apps/pyem-git/csparc2star.py", line 107, in main
    df = star.augment_star_ucsf(df, inplace=True)
  File "/home/scicons/cascade/apps/pyem-git/pyem/star.py", line 637, in augment_star_ucsf
    if "@" in df.iloc[0][Relion.IMAGE_NAME]:
  File "/home/scicons/cascade/apps/python/3.6/lib/python3.6/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/scicons/cascade/apps/python/3.6/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4419, in get_value
    raise e1
  File "/home/scicons/cascade/apps/python/3.6/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4405, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rlnImageName'

**Comment by phexorb** [comment]
Same here.  Runs well without --copy-micrograph-coordinates, but gets similar "KeyError: 'rlnImageName'" with --copy-micrograph-coordinates. Was working properly before upgrading Cryosparc recently.

csparc2star.py particles_selected.cs J132_passthrough_particles_selected.cs csJ132_selected.star --copy-micrograph-coordinates relion_original.star --loglevel debug
Detected CryoSPARC 2+ .cs file
Reading primary file
Assigning pose from 2D classes
Assigning skew angle from 2D classification
Copying image size
Reading auxiliary file J132_passthrough_particles_selected.cs
Trying to merge: ctf/type, ctf/exp_group_id, ctf/accel_kv, ctf/cs_mm, ctf/amp_contrast, ctf/df1_A, ctf/df2_A, ctf/df_angle_rad, ctf/phase_shift_rad, ctf/scale, ctf/scale_const, ctf/shift_A, ctf/tilt_A, ctf/trefoil_A, ctf/tetra_A, ctf/anisomag, ctf/bfactor, pick_stats/ncc_score, pick_stats/power, pick_stats/template_idx, pick_stats/angle_rad
Merging: rlnDefocusU, rlnAmplitudeContrast, rlnCtfBfactor, rlnDefocusAngle, rlnPhaseShift, rlnSphericalAberration, rlnOpticsGroup, rlnVoltage, rlnDefocusV
Directly copied fields: ucsfUid, ucsfImageIndex, rlnImagePixelSize, ucsfImagePath, rlnRandomSubset, rlnOriginX, rlnOriginY, rlnAnglePsi, rlnClassNumber, rlnImageSize, rlnDefocusU, rlnAmplitudeContrast, rlnCtfBfactor, rlnDefocusAngle, rlnPhaseShift, rlnSphericalAberration, rlnOpticsGroup, rlnVoltage, rlnDefocusV
Converting DEFOCUSANGLE from radians to degrees
Converting PHASESHIFT from degrees to radians
Changing RANDOMSUBSET to 1-based index
Changing CLASS to 1-based index
Changing OPTICSGROUP to 1-based index
Converting ANGLEPSI from degrees to radians
Traceback (most recent call last):
  File "/home/usr/.conda/envs/pyem38a/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rlnImageName'

**Comment by kdr400219** [comment]
Since this is picking up some steam, I figured out a workaround a little bit ago - basically re-invented the wheel, but perhaps it's useful to the few people experiencing similar problems. 

- In CS, import Relion motion-corrected micrographs. Import your Relion particles, remove UID, connecting the previously imported Relion micrographs. 
- Refine particles, export particles so all passthrough info is integrated into one file. 
- use csparc2star.py **without** using --copy-micrograph-coordinates, also --inverty

```
csparc2star.py particles_exported.cs new-relion-coordinates.star --inverty
``` 
- replace the file paths in the new .star file with the appropriate Relion file paths from the subfolder in MotionCorr/jobXXX/ - basically, the extracted particle paths and the micrograph paths should match up to those of Relion. This file can be used directly for polishing. 

YMMV,  but this has worked fine in my hands.

**Comment by asarnow** [comment]
@kdr400219 this is a good solution, I have also done this.

@ the rest, I'm sorry the error message isn't that informative. I am pretty sure your rlnImageName fields do not match between the two files. Please inspect your star files and see if it's really the case that they both have rlnImageName fields with identical rlnImageName (or rlnImageOriginalName) basenames. (Or, exactly identical micrograph names and coordinates).

**Comment by cdienem** [comment]
We are having the same issue here after using the latest pyem (0.61) `KeyError: 'rlnImageName'`. The star file that was originally imported to cryoSPARC has the following header:

input.star
```
data_optics

loop_
_rlnOpticsGroup #1
_rlnOpticsGroupName #2
_rlnAmplitudeContrast #3
_rlnSphericalAberration #4
_rlnVoltage #5
_rlnImagePixelSize #6
_rlnImageSize #7
_rlnImageDimensionality #8
_rlnBeamTiltX #9
_rlnBeamTiltY #10
_rlnOddZernike #11
_rlnEvenZernike #12
_rlnCtfDataAreCtfPremultiplied #13

[...]

data_particles

loop_
_rlnImageName #1
_rlnMicrographName #2
_rlnCoordinateX #3
_rlnCoordinateY #4
_rlnAnglePsi #5
_rlnOriginXAngst #6
_rlnOriginYAngst #7
_rlnDefocusU #8
_rlnDefocusV #9
_rlnDefocusAngle #10
_rlnPhaseShift #11
_rlnCtfBfactor #12
_rlnOpticsGroup #13
_rlnRandomSubset #14
_rlnClassNumber #15
_rlnAngleRot #16
_rlnAngleTilt #17
_rlnNormCorrection #18
_rlnLogLikeliContribution #19
_rlnMaxValueProbDistribution #20
_rlnNrOfSignificantSamples #21
_rlnGroupName #22
_rlnCtfScalefactor #23
_rlnGroupNumber #24
_rlnImageOriginalName #25 
```

The command is `csparc2relion.py --copy-micrograph-coordinates input.star --boxsize 200 --strip-uid 1 CS-to-Relion/*.cs output.star`

the CS files are `_ctf.cd` and `_align3D.cs`. 

We tested this with files that were converted successfully before (with some older pyem version), and they now fail with the same error as above.

**Comment by cdienem** [comment]
Update from here. When using an older pyem (commit 9c16200 with python 3.8 and numpy<1.20), it all works as expected with the same star files.

**Comment by asarnow** [comment]
I figured it out, fixed now. I also changed most of my debug statements to info so you can get them on `--loglevel=info` without seeing a ton of debug messages from pandas. Reopen if not fixed. Remember to fix your links to the command line programs as they have been moved within the pyem repo.
