### ISSUE TITLE
Error while Creating link during Relion project setup

### ISSUE THREAD

**Issue by rajssai** [asarnow/pyem#111]
I am trying to create a link of extract job in relion-project directory as below

cd relion-project
mkdir -p J228/extract
cd J228/extract
ln -s /path/to/cryosparc/P7/J228/extract/*.mrc -t .

Giving following error

-bash: /bin/ln: Argument list too long 

Please advise how to create a link for these file having approx 100000 particles.

**Comment by derpaule** [comment]
In case others encounter this problem.
Following line worked for me:

find /$JOB/extract/ -name "*.mrc" -print0 | xargs -0 -I{} ln -s {} .

Could be added to the wiki maybe?

Best,
Tim
