### ISSUE TITLE
Pyem installation problem

### ISSUE THREAD

**Issue by shl4014** [asarnow/pyem#113]
Hi,

I'm trying to install pyem on my new macbook M3 Pro computer.

I'm trying to follow the installation instructions on the installation wiki page using miniconda.
I already installed miniconda, and followed all subsequent instructions with seemingly no problem, but when I try to create a miniconda environment, I encounter a problem with python.
Specifically, when I type in "conda install -c conda-forge pyfftw healpy pathos", I get the following errors:

Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pyfftw-0.12.0-py310h5e9c6ea_3 requires python >=3.10,<3.11.0a0 *_cpython, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ pyfftw is not installable because there are no viable options
   ├─ pyfftw [0.12.0|0.13.0|0.13.1] would require
   │  └─ python >=3.10,<3.11.0a0 *_cpython, which conflicts with any installable versions previously reported;
   ├─ pyfftw 0.12.0 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   ├─ pyfftw 0.12.0 would require
   │  └─ python >=3.8,<3.9.0a0 *_cpython, which conflicts with any installable versions previously reported;
   ├─ pyfftw 0.12.0 would require
   │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.12.0|0.13.0|0.13.1] would require
   │  └─ python >=3.9,<3.10.0a0 *_cpython, which conflicts with any installable versions previously reported;
   └─ pyfftw [0.13.0|0.13.1] would require
      └─ python >=3.11,<3.12.0a0 *_cpython, which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')

I should note that I tried installing python 3.12 on my computer, but that does not seem to fix the problem.

Any ideas how I can solve this problem?
Needless to say that installing pyem is extremely important for my project...

Thank you!!!

**Comment by asarnow** [comment]
Hmm, are you using miniconda? Can you try with miniforge3 / mamba instead? Highly recommend on Apple silicon Macs, those packages are actually native and much more performant. It's working on my M1 MBP but I can create a new environment and try to reproduce this.

**Comment by gghanim** [comment]
This worked for me:

conda create -n pyem -c conda-forge pyfftw healpy pathos
conda activate pyem
conda install numpy scipy matplotlib seaborn numba pandas natsort

**Comment by asarnow** [comment]
@gghanim Were you using miniforge?
@shl4014 I recommend you use miniforge3 instead of miniconda, it will give you M-series native numerical libraries, also it's what I'm using/testing on my M1 MBP.

**Comment by ts387** [comment]
@asarnow I am getting the same installation error on Linux. Any suggestions?

```
bash-5.1$ conda install -c conda-forge pyfftw healpy pathos
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE                                                                                                                                              failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pyfftw-0.10.1-np110py27_0 requires python 2.7*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ pyfftw is not installable because there are no viable options
   ├─ pyfftw [0.10.1|0.10.3|...|0.12.0] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.10.1|0.10.3|0.10.4] would require
   │  └─ python 3.4* , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.10.1|0.10.3|0.10.4] would require
   │  └─ python [3.5* |>=3.5,<3.6.0a0 ], which conflicts with any installable versions previously reported;
   ├─ pyfftw 0.10.4 would require
   │  └─ python 3.6* , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.10.4|0.11.0|0.11.1|0.12.0] would require
   │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.10.4|0.11.0|0.11.1|0.12.0|0.13.0] would require
   │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.11.1|0.12.0|0.13.0|0.13.1] would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.12.0|0.13.0|0.13.1] would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ pyfftw [0.12.0|0.13.0|0.13.1] would require
   │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
   └─ pyfftw [0.13.0|0.13.1] would require
      └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by asarnow** [comment]
pyfftw doesn't work on Python 3.12 for some reason. Please use 3.9 - 3.11.

**Comment by asarnow** [comment]
Closing. Hope conda-forge gets to my PR eventually.
