### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by boltface1** [asarnow/pyem#117]
I think the installation instructions may have been deleted from the Wiki in the latest round of updates. Please could you put them back up again?

**Comment by asarnow** [comment]
If you wait one more day you will be able to `conda install -c conda-forge pyem`!.

If you can't wait:

```
mamba create -n pyem python=3.11
mamba activate pyem
mamba install numba numpy scipy matplotlib seaborn pandas pathos pyfftw healpy natsort starfile ipython
git clone https://github.com/asarnow/pyem.git
cd pyem
pip install --no-dependencies -e .
export PATH=$(realpath pyem/cli):$PATH
```

**Comment by boltface1** [comment]
Thank you!

**Comment by wsatbluesky** [comment]
`conda install -c conda-forge pyem`  It doesn't work yet.

**Comment by asarnow** [comment]
I didn't realize it would take so long for review.

https://github.com/conda-forge/staged-recipes/pull/26646

**Comment by wsatbluesky** [comment]
Never mind. Thank you for making installation easier.

**Comment by asarnow** [comment]
@xingxingjiukunkun You can install pyem in whatever environment you wish as long the dependencies are present. If you ignore dependencies, you can also install only the ones that are needed for a particular program, for example I *think* that if you skip `pyfftw` csparc2star.py would still run.

**Comment by asarnow** [comment]
I got tired of waiting so I pushed my readme update but added a "coming soon" note to the conda install. Will remove those headings when conda-forge reviewers get to my package.
