### ISSUE TITLE
Installing pyem from git repository tagged 0.61 claims installing version 0.5

### ISSUE THREAD

**Issue by cdienem** [asarnow/pyem#118]
When installing pyem by cloning the repository tagged with 0.61, at the end of the isntallation I still get the output `Successfully installed pyem-0.5`. This is not a big issue but confusing.

Just for reference, here my installation procedure (Miniconda, CentOS 7).

```bash
#!/bin/bash
# Installs pyem

### SETTINGS ###
INSTALL_TO=/opt
PROGRAM=pyem
VERSION=0.61

# Where to find conda
CONDA_ROOT=/opt/miniconda/miniconda-default

INSTALLER=https://github.com/asarnow/pyem.git

### INSTALL ###

# Create software location
mkdir -p $INSTALL_TO/$PROGRAM/$PROGRAM-$VERSION
cd $INSTALL_TO/$PROGRAM

git clone -b v$VERSION $INSTALLER $PROGRAM-$VERSION
cd $PROGRAM-$VERSION

# Activate conda and create the environment
source $CONDA_ROOT/etc/profile.d/conda.sh


conda create -n $PROGRAM-$VERSION python=3.11 -y
conda activate $PROGRAM-$VERSION
conda install numba numpy scipy matplotlib seaborn pandas pathos pyfftw healpy natsort starfile ipython -c conda-forge -y
pip install --no-dependencies -e .
#export PATH=$(realpath pyem/cli):$PATH -> will be in the module

### CLEAN UP ###
# Cleaning leftover cached files
conda clean --all -y
```

**Comment by asarnow** [comment]
FYI The master branch HEAD is always going to be the "current version" that I support. The version number 0.5 was so I could get a zenodo DOI. The new version numbers > 0.6 are so the conda-forge package (whenever it gets accepted...) has an archive to verify SHA256 hash.

I'll update the setup.py version number to match the conda one sometime soon.
