### ISSUE TITLE
Incorrect requirement name `matplotlib-base`

### ISSUE THREAD

**Issue by ccoulombe** [asarnow/pyem#119]
`matplotlib-base` does not exists on PyPI, it seems to be a conda related name. It seems it was correctly name before 119f0ca.

One could use `extras_require` to specify standard requirements, and conda specific requirements if neded

**Comment by asarnow** [comment]
Thanks for pointing that out. I fixed the PyPi style install files (setup.py, requirements.txt) to refer to matplotlib. The -base package is a conda-forge thing to keep requirements a bit more light weight.
