### ISSUE TITLE
installing pyem

### ISSUE THREAD

**Issue by hsosa509** [asarnow/pyem#120]
Hi  after  following the pyem installation instructions I get the following errors:
------------------------------------------------------------------------------
>mamba install numba numpy scipy matplotlib seaborn pandas pathos pyfftw healpy natsort starfile 
Looking for: ['numba', 'numpy', 'scipy', 'matplotlib', 'seaborn', 'pandas', 'pathos', 'pyfftw', 'healpy', 'natsort', 'starfile']

pkgs/main/linux-64                                          Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/linux-64                                             Using cache
pkgs/r/noarch                                               Using cache

Pinned packages:
  - python 3.11.*

Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested pyfftw
  - nothing provides requested healpy
  - nothing provides requested starfile

The environment can't be solved, aborting the operation
---------------------------------------------------------------------------
Any suggestions of how to proceed form here ?  I am aware hat this may be an issue of installing the indicated packages (??) but  I am not  super  familiar with conda or mamba installations so any suggestions about  how to proceed will be appreciated.

Thanks

**Comment by asarnow** [comment]
You need to use conda-forge, either by using miniforge3 or by including -c conda-forge in your install command.

Just tested an install with miniforge3 & mamba, if you have conda-forge you will be able to get those dependencies.

**Comment by hsosa509** [comment]
Following up  on my previous message after a while the installation  failed with the following errors:

conda install -c conda-forge pyem
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - pyem -> healpy[version='>=1.11'] -> __glibc[version='>=2.17,<3.0.a0']

___________________________________
Hernando Sosa, PhD.
Dept. of Biochemistry
Albert Einstein College of Medicine
1300 Morris Park Av.
Bronx NY 10461
phone (718) 430-3456
emai:  ***@***.******@***.***>edu
___________________________________


________________________________

**Comment by asarnow** [comment]
This environment seems to have its own incompatible glibc libraries. Perhaps due to a previous package requirement. I suggest updating conda and using a new environment.

I also recommend using miniforge & mamba, the packages are generally more up-to-date and mamba solves dependencies roughly 100 times faster than conda.

**Comment by asarnow** [comment]
I tested using a (pretty old) miniconda3 to install pyem under python 3.9, and it worked as expected. So I suspect something else in your environment is preventing installation of the right glibc version.

**Comment by hsosa509** [comment]
I updated conda, created a new environemt (HSpyem)
and  got this far:

>mamba create -n HSpyem python=3.11
>mamba activate HSpyem
(HSpyem)>mamba install numba numpy scipy matplotlib seaborn pandas pathos pyfftw healpy natsort starfile

Everything seems to have been installed (at least with no error messages).

So I have some new questions now: Where  are the scripts  located?   Is the  pyem scripts directory added to  PYTHONPATH  in this  environment?

I see that there is  a new pyem directory in my home directory and a setup.py file in this directory. Should I now  run  setup.py ?

Trying to  run csparc2star.py just by typing the name of the script  from the home directory results in error (see below).  Should I add a directory to PATH? which one?



--------------------------------
(HSpyem)>python csparc2star.py
python: can't open file '/home/cryosparc_user/csparc2star.py': [Errno 2] No such file or directory
-------------------------------------

Thanks again

H.



________________________________

**Comment by hsosa509** [comment]
Dear Daniel,


Could you tell me what is the command to convert particles from a cryosparc helical refinement job  to a relion starfile. (what cs files to use, options etc).

csparc2star. py  XX.cs ???


Thank  you

Best

H.



________________________________
