### ISSUE TITLE
pyem algo module error with star.py

### ISSUE THREAD

**Issue by domgutier** [asarnow/pyem#13]
Hello,
I am getting the message below when I run pyem/pyem/star.py --copy-micrograph-coordinates particles.star cryosparc.star cryosparc_withcoords.star. Should I have done anything to the script? All I did was git clone it to my directory.

Traceback (most recent call last):
  File "pyem/pyem/star.py", line 30, in <module>
    from pyem.algo import query_connected
ImportError: No module named pyem.algo

Best,
Dominique

**Comment by asarnow** [comment]
You must install the library, as described in the [wiki](https://github.com/asarnow/pyem/wiki/Install-pyem).

Best,
-da

**Comment by domgutier** [comment]
Hello,
Thank You for the link Da!  I have come across a problem with the last step pip install -e .
I see this message Failed building wheel for pyfftw 
                       ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/usr/bin/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-84paCL/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3T7OfP-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-84paCL/pyfftw/

Would I need to install pyfftw or should this be part of miniconda2?
Best,
Dominique

**Comment by asarnow** [comment]
Great. Pyfftw has C components so it's more sensitive to the environment. I was going to suggest just removing it from the requirements since it's not needed for the star.py script, but having it is better in case you decide to use projection_subtraction.py at some point.
