### ISSUE TITLE
csparc2star.py

### ISSUE THREAD

**Issue by xzhang1999** [asarnow/pyem#14]
Hi, Asarnow,

Thanks for this wonderful program. I tried ii on three datasets processed with cryosparc, after converting the .csv files to .star and computing maps with relion_reconstruct, one dataset worked fine but maps of other two datsets were incorrect. Furthermore, for the working dataset, I revised the .star file to point to the same datset but with phase_flipped, then computed a map with relion_reconstruct, but the map is incorrect. Any suggestions would be greatly appreciated. Thanks a lot.

Best regards,
Xing

**Comment by asarnow** [comment]
Hi Xing, thanks for trying my program! As you found, `csparc2star.py` will correctly convert the available data to a format Relion understands (if Relion *can* understand it at all). I'm guessing that something else is going on with your other .star files.

Is there any symmetry (you must use the correct `--sym` with Relion)? Did you remember to remove `--ctf` when reconstructing the phase-flipped data? Have you been setting `--angpix` correctly? Also, `--maxres` should be Nyquist or lower, it will make the reconstruction much nicer. Also, `relion_reconstruct` does not set the pixel size in the map file, so in Chimera under the Volume Viewer > Features > Coordinate pane you will need to set the pixel size manually.

Can you check those things first, and then report back? Thanks!

**Comment by xzhang1999** [comment]
Thanks much, Daniel,

You are right that I mistakenly use both --ctf and --ctf_phase_flipped in relion_reconstruct, and it looks ok after removing --ctf option for the phase flipped data, and other differences may result from different filterings.

Would you please include an option of scaling origins in the csparc2relion.py? (Does cryoSPARC use pixel or angstrom for particle origins?). For big particles such as viruses, I usually use the binning x2 or x4 datasets in cryoSPARC and need to reconstruct and refine maps using the binning x1 dataset with relion or frealign.

Thank you very much.



Best regards,
Xing
 
From: Daniel Asarnow
Date: 2018-04-24 12:41
To: asarnow/pyem
CC: xzhang1999; Author
Subject: Re: [asarnow/pyem] csparc2star.py (#14)
Hi Xing, thanks for trying my program! As you found, csparc2star.py will correctly convert the available data to a format Relion understands (if Relion can understand it at all). I'm guessing that something else is going on with your other .star files.
Is there any symmetry (you must use the correct --sym with Relion)? Did you remember to remove --ctf when reconstructing the phase-flipped data? Have you been setting --angpix correctly? Also, --maxres should be Nyquist or lower, it will make the reconstruction much nicer. Also, relion_reconstruct does not set the pixel size in the map file, so in Chimera under the Volume Viewer > Features > Coordinate pane you will need to set the pixel size manually.
Can you check those things first, and then report back? Thanks!

**Comment by xzhang1999** [comment]
Thanks much, Daniel,



Best regards,
Xing
 
From: Daniel Asarnow
Date: 2018-04-25 01:17
To: asarnow/pyem
CC: xzhang1999; Author
Subject: Re: [asarnow/pyem] csparc2star.py (#14)
Glad it's working!

As to scaling origins, that feature is implemented for star files in the
star.py program. Check out the --help output, there are many other useful
operations as well.

I'm closing this issue since there isn't a pyem bug.
