### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by robinbinchen** [asarnow/pyem#15]
Hi,
I'm now install the pyem using the miniconda, and when I try to run the csparc2star.py, it shows the following error:

> Traceback (most recent call last):
>   File "/Users/robinchen/PycharmProjects/pyem/csparc2star.py", line 27, in <module>
>     from pyem import metadata
>   File "/Users/robinchen/PycharmProjects/pyem/pyem/__init__.py", line 3, in <module>
>     from . import metadata
>   File "/Users/robinchen/PycharmProjects/pyem/pyem/metadata.py", line 22, in <module>
>     from . import star
>   File "/Users/robinchen/PycharmProjects/pyem/pyem/star.py", line 31, in <module>
>     from pyem.util import rot2euler
>   File "/Users/robinchen/PycharmProjects/pyem/pyem/util/__init__.py", line 5, in <module>
>     from .quat_numba import *
>   File "/Users/robinchen/PycharmProjects/pyem/pyem/util/quat_numba.py", line 30, in <module>
>     "(m)->(m)", nopython=True, cache=True)
>   File "/Users/robinchen/anaconda/lib/python2.7/site-packages/numba/npyufunc/decorators.py", line 165, in wrap
>     guvec.add(fty)
>   File "/Users/robinchen/anaconda/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 169, in add
>     self.nb_func, targetoptions, sig)
>   File "/Users/robinchen/anaconda/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 92, in _compile_element_wise_function
>     cres = nb_func.compile(sig, **targetoptions)
>   File "/Users/robinchen/anaconda/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 63, in compile
>     self.targetdescr.options.parse_as_flags(flags, topt)
>   File "/Users/robinchen/anaconda/lib/python2.7/site-packages/numba/targets/options.py", line 26, in parse_as_flags
>     opt.from_dict(options)
>   File "/Users/robinchen/anaconda/lib/python2.7/site-packages/numba/targets/options.py", line 19, in from_dict
>     raise KeyError(fmt % k)
> KeyError: "Does not support option: 'cache'"

I try different version of python and update every package, but still don't fix it.

Please let me know if I can try other way to fix it

Thank you!

Robin

**Comment by asarnow** [comment]
Hi Robin,
Did you install miniconda to a directory named anaconda? The default is miniconda2 - I just want to make sure you are using the right python instance. The minconda bin directory should be added to your path in front of any other python instances.

**Comment by asarnow** [comment]
Probable user error / no response, closing.
