### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by pherepanov** [asarnow/pyem#18]
Dear Daniel, 

csparc2star generates this error: **TypeError: <lambda>() got an unexpected keyword argument 'result_type'**

Am I missing something on my system? 

Peter

**Comment by pherepanov** [comment]
oops, I forgot **--upgrade** option again. 
It all seems to work now,

Thank you for developing this very useful tool! 

Peter

**Comment by asarnow** [comment]
Great, no problem. For anyone else reading this, the error is caused by out-of-date Pandas version.
