### ISSUE TITLE
y-flip on the coordinates for relion3

### ISSUE THREAD

**Issue by alburse** [asarnow/pyem#22]
Dear Daniel Asarnow @asarnow

I am using your csparc2star.py program. It is very useful for me. However I encounter a fundamental problem with the coordinates in my case. The coordinates that I get from your program are correct but the way relion3-beta and cryosparc read micrographs is different in my hands. Basically there is a y-flip on the coordinates (for tif files) on cryosparc compared to relion3-beta. The movie pixel information on cryosparc shows movie_blob/shape:  [ 40 3710 3838] and apparently 3710 is the y dimension. When I subtract the y coordinate reported on the star file from your program from 3710, I get the correct value. If I am not mistaken, do you think you can easily implement this? 

Thank you for your contribution to the community.

Alpay

**Comment by asarnow** [comment]
Hi @alburse. Thanks for the report. Is it also the case with micrographs as opposed to movies?

**Comment by alburse** [comment]
Yes it is. This actually depends on if you have a y flip due to an energy filter or not. Micrographs from another microscope without energy filter are read the same.

**Comment by asarnow** [comment]
By "the same" do you mean it works? There is a "flip y" and "flip x" option in the Extract from Micrographs job in cryoSPARC - maybe that's how we should handle it?

**Comment by alburse** [comment]
I think I tried that but that was not working the same way. I think the
best would be cryosparc to be able to import movies with a flip.

**Comment by asarnow** [comment]
What job type are you exporting? Can you see the 'location/micrograph_shape' parameter (as that's what I'm using in my code)? Usually cryoSPARC uses the same coordinate convention as Relion.

**Comment by asarnow** [comment]
Since this appears to be an internal cryoSPARC issue, I am closing this (at least for now).
