### ISSUE TITLE
csparc2star.py csparc2star.py: command not found; ImportError: No module named numpy

### ISSUE THREAD

**Issue by ZhenColumbia** [asarnow/pyem#24]
@asarnow Hi Daniel,

I am trying to convert cs file from cryosparc2 into star files and encountered several question:

1. The first line in csparc2star.py is: #!/usr/bin/env python2.7
Does that mean that I have to use python 2.7 as assigned version? I have updated my mac with python3.7. I am not sure if python3.7 caused the problem.
2. A very frequent error (I tried to install on different computers and this happened a lot) that happened when I want to use csparc2.star is: csparc2star.py: command not found
Do you know why this happened and how to solve this problem?

3. Sometimes, it seems that csparc2star.py was about to run and I have encountered many problems regarding numpy. One of the problems is ImportError: No module named numpy. Another error is ImportError: numpy.core.multiarray failed to import. PS: I have updated numpy to 1.15.4
I also followed the suggestion from this post: https://github.com/tensorflow/tensorflow/issues/559
I deleted and re-updated all numpy that I could find on my laptop. The problem was still not solved.

Thank you very much in advance for your time and help.

Best,
Zhen

**Comment by asarnow** [comment]
Hi Zhen,

1. It's using the environment's python2.7. That's whatever that command is in your environment.
2. You haven't put the programs on your PATH. You should search for a command line tutorial about the PATH variable. I recommend you make symbolic links in a directory on your PATH which point to the python files in the git repo.
3. A sufficiently recent version of numpy (and probably many other required packages) is not installed in the python that's being used to run the program. Again, make sure you use the environment's python2.7 to setup the dependencies. You can always run the programs using a specific python binary, the #! line is just used to let the environment select the interpreter automatically when the program is called like an executable.

I recommend you install pyem using the [method in the wiki](https://github.com/asarnow/pyem/wiki/Install-pyem-with-Miniconda), it will make handling the dependencies and not messing with other copies of python easier.

**Comment by asarnow** [comment]
PS Although the issue is closed (because there's no pyem bug), please feel free to continue asking questions here, the thread will still work and I will receive notifications.

**Comment by ZhenColumbia** [comment]
Hi Daniel,

Thank you very much for the helpful suggestions. I did watch the variable path tutorial and read all related issues, but I still messed with dependencies and different copies of pythons:( I will try your suggestions and hopefully it will work. Thank you again and Happy New Year!!

Best,

Zhen

在 2019年1月1日，18:47，Daniel Asarnow <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #24<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_asarnow_pyem_issues_24&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=YktHMsI1j1-F0zYzVTZjw8KHFiPAQj-YfcfnrWOyafk&m=X7EL-qcbrBVrs-h7InbTDEMAS7H1-XMEj0gBTkInUY8&s=ErNcGLGD0p8K8204llPaa0efYndib0wV5OwWl4fD2-s&e=>.
