### ISSUE TITLE
csparc2star.py ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by sunny1226** [asarnow/pyem#27]
Hi, after I reinstalled latest version of pyem, I found csparc2star.py not work. Did you have any suggestions? Here are the loglevel:
Detected CryoSPARC 2+ .cs file
Reading passthrough file
Particle passthrough detected
Concatenating passthrough fields: alignments2D/split, alignments2D/shift, alignments2D/pose, alignments2D/psize_A, alignments2D/error, alignments2D/error_min, alignments2D/resid_pow, alignments2D/slice_pow, alignments2D/image_pow, alignments2D/cross_cor, alignments2D/alpha, alignments2D/weight, alignments2D/pose_ess, alignments2D/shift_ess, alignments2D/class_posterior, alignments2D/class, alignments2D/class_ess
Creating particle DataFrame from recarray
Directly copied fields: rlnDefocusAngle, rlnDetectorPixelSize, rlnCtfFigureOfMerit, rlnSphericalAberration, rlnAmplitudeContrast, rlnCtfMaxResolution, rlnVoltage, rlnDefocusU, rlnPhaseShift, rlnDefocusV, rlnImageName, rlnMagnification
Converting DEFOCUSANGLE from degrees to radians
Converting PHASESHIFT from degrees to radians
Collecting particle parameters from most likely classes
Columns must be same length as key
A passthrough file may be required (check inside the cryoSPARC 2+ job directory)
Columns must be same length as key
Traceback (most recent call last):
  File "/opt/pyem/csparc2star.py", line 42, in main
    df = metadata.parse_cryosparc_2_cs(cs, passthrough=args.passthrough, minphic=args.minphic)
  File "/opt/pyem/pyem/metadata.py", line 356, in parse_cryosparc_2_cs
    [cs[names[c]][i] for i, c in enumerate(cls)]))
  File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 2352, in __setitem__
    self._setitem_array(key, value)
  File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 2376, in _setitem_array
    raise ValueError('Columns must be same length as key')
ValueError: Columns must be same length as key
And here are the dependency versions: 
future==0.17.1
numba==0.42.0
numpy==1.15.3 (I tried 1.14.0, 1.15.4 and 1.16.0, none of them worked)
scipy==1.2.0
matplotlib==2.2.3
seaborn==0.9.0
pandas==0.23.4
pathos==0.2.2.1
pyfftw==0.11.1
And we used latest pyem version now. 
Looking for your reply.

**Comment by sunny1226** [comment]
Thanks. I found that remove passthrough parameter make csparc2star.py works. Please close the issue.

**Comment by asarnow** [comment]
Great, thanks for the update.

**Comment by dhaselb** [comment]
Hi, how do you remove the passthrough parameter? 

Best,

David
