### ISSUE TITLE
csparc2star.py incorrect offsets if cs file comes from a refinement with a box size differing from original box

### ISSUE THREAD

**Issue by olibclarke** [asarnow/pyem#30]
Hi Dan,

Not sure if this is an avoidable issue without input from cryoSPARC devs, but I have noticed that if I take particles from a refinement that was performed with a different box size (and hence pixel size) to the original particles, then the offsets in the output star file are wrong (or correct for whatever pixel size was used in the refinement, but wrong for the pixel size in the output star file).

So for example, if I have binned particles to 4Å/pixel but then refine interpolating to 2Å per pixel, the output offsets are wrong (and will give bad results if used for recentering particles).

Cheers
Oli

**Comment by asarnow** [comment]
There might be another field for the refinement size, I'll check. Otherwise, I'll add `--apix` parameters.

Thanks a lot for the report.

**Comment by asarnow** [comment]
The only provided fields are `blob/shape` and `blob/psize_A` which refer to the original box and pixel size. As in Relion, shifts are always in pixels wrt to current pixel size. The formula `real_box / refine_box * shifts` will give the correct values and only requires a `--boxsize` argument for the refinement box.

**Comment by asarnow** [comment]
@olibclarke If you get a chance to try the `--boxsize` argument, please let me know how it goes! Thanks again.
