### ISSUE TITLE
from cryosparc to relion

### ISSUE THREAD

**Issue by Omid1985** [asarnow/pyem#34]
Dear @asarnow,

Thank you first of all for an amazing script. I have no issues importing relion particles into cryosparc and back. However, I am having some problems converting particles from 2D classification (originally extracted from cryosparc) into relion .star file. 

I ran the following command: /data/CRYOSPARC/pyem/csparc2star.py --copy-micrograph-coordinates --passthrough /Cryosparc_job_2D/passthrough_selected.cs  /data/CRYOSPARC/USERS/Omid/2D_job/particles_selected.cs from_cryosparc.star

The command seem to give me an output, but in relion I cannot get the particles imported properly. I think part of the issue is that the particles were extracted in cryosparc from a CTF corrected images there, and the coordinate system is different than in the CTF corrected images in relion. 

For each image it says 0 particles get extracted in relion. 
Is there a way to correct or get around the problem?  

I am using cryosparc 2.9 and relion 3.0

Best,
Omid

**Comment by asarnow** [comment]
Hi Omid,
That's not how the arguments are used. `--copy-micrograph-coordinates` is for particles extracted outside cryoSPARC, it needs a .star file as input. The `--passthrough` argument used to be used for getting more info from other .cs files such as coordinates, but it's now obsolete.

Instead you simply give a list of .cs files, starting with the base one. They will all be merged into the output .star file. Only missing information is included, and priority is given by the list order.
`csparc2star.py job_particles.cs passthrough.cs other.cs ... out.star`

**Comment by Omid1985** [comment]
Hi Daniel,

Thank you for the quick reply. That makes a lot more sense. I'll give that a go and see how it goes. 

Best,
Omid
