### ISSUE TITLE
Export particles coordinate

### ISSUE THREAD

**Issue by wxh180** [asarnow/pyem#35]
Dear Dan,
If I want to export the coordinates of particles when I convert from cs to star, which particles cs files should I use?
"--copy-micrograph-coordinates",  "Source for micrograph paths and particle coordinates (file or quoted glob)",
What do you mean here "quoted glob"? Thanks!
Best regards,
Wei

**Comment by asarnow** [comment]
You use the job .cs file and any additional .cs file (such as one with coordinates) as described in the [forum post](https://discuss.cryosparc.com/t/csparc2star-py-final-update/3073). Eventually I will update the instructions in the wiki here. `--copy-micrograph-coordinates` is only when the coordinates are in the .star file used for importing.
