### ISSUE TITLE
ImportError: No module named pandas

### ISSUE THREAD

**Issue by mtuijtel** [asarnow/pyem#38]
Hi,

I saw related threats regarding the panda-module, but these fixes didn't work for me.

When I try to execute:
`csparc2star.py /P6/J46/passthrough_particles_selected.cs /P6/J46/passthrough_particles_selected.star`
I get the following error:
```
Traceback (most recent call last):
  File "/root/pyem/csparc2star.py", line 26, in <module>
    import pandas as pd
ImportError: No module named pandas
```
When I try:

```
# which pip
/usr/local/EMAN2/bin/pip
# which python
/usr/local/EMAN2/bin/python
# pip --version
pip 10.0.1 from /usr/local/EMAN2/lib/python2.7/site-packages/pip (python 2.7)

```

So I guess that's what the problem is, as also mentioned in the other threads. 
I don't know how to "hide EMAN python", as was mentioned elsewhere. I'd like to use both EMAN2 and csparc2star if at all possible.

The strange thing is, it worked before. Or at least, the command csparc2star ran smoothly, but then I couldn't open the particles in relion, as it was unable to find micropgraphXX.mrc, or something related to that. But one problem at the time ;-)

Maybe unrelated, but I installed pyem as root in: /root/pyem/. Could that cause issues?

Many thanks in advance for your help, much appreciated.
Regards,
Maarten

**Comment by asarnow** [comment]
Hi Maarten,
You just need to move the EMAN2 python later in your path. When EMAN2 is being added in your .bashrc file, it should come after the rest of the PATH and not before.

**Comment by mtuijtel** [comment]
Thank Daniel, that worked like a charm.
My path was a bit of a mess with many repeats, so I also cleaned it up a bit.
