### ISSUE TITLE
No module named pyem.geom

### ISSUE THREAD

**Issue by domgutier** [asarnow/pyem#39]
Hello, 

I get the message below when I try and use star.py. 

Traceback (most recent call last):
  File "/home/user/pyem/pyem/star.py", line 26, in <module>
    from pyem.geom import e2r_vec
ImportError: No module named pyem.geom

How can I get the module?

Thank you,
Dominique

**Comment by asarnow** [comment]
Hi Dominique,
The package needs to be installed - or you can change to the pyem directory to work from. If you installed the package, maybe you also have another copy of python higher up in your PATH.

You can switch to the pyem directory and run `pip install --user -e .`, that's the easiest way for now.
