### ISSUE TITLE
Exporting particles to relion imports micrographs

### ISSUE THREAD

**Issue by mtuijtel** [asarnow/pyem#40]
Hi, 
My goal is to either export particles from cryosparc into relion, or alternatively to export only the locations of the particles, so something like .box files, which I can then use to extract the selected particles in relion.

I've successfully created a .star of particles after 2D classification and selection, using:
`csparc2star.py /P6/J46/passthrough_particles_selected.cs /P6/J46/passthrough_particles_selected.star`

I can also import it in relion, using the Import job, linking to "passthrough_particles_selected.star", with Node type: Particles STAR file (.star), but when I try to open some particles for inspection, it opens micrographs instead. 

I have the feeling I'm missing something obvious here, but can't figure it out.

I've opened the .star file, and I get the following info:
```
data_images
loop_
_rlnMicrographName #1 
_rlnCoordinateX #2 
_rlnCoordinateY #3 
_rlnAnglePsi #4 
_rlnOriginX #5 
_rlnOriginY #6 
_rlnVoltage #7 
_rlnMagnification #8 
_rlnDefocusU #9 
_rlnDefocusV #10 
_rlnDefocusAngle #11 
_rlnSphericalAberration #12 
_rlnPhaseShift #13 
_rlnAmplitudeContrast #14 
_rlnClassNumber #15 
_rlnRandomSubset #16 
```
followed by all the data.

If I open another random particles.star file created by relion itself, I get: 
```
# RELION; version 3.0

data_

loop_ 
_rlnCoordinateX #1 
_rlnCoordinateY #2 
_rlnImageName #3 
_rlnMicrographName #4 
_rlnMagnification #5 
_rlnDetectorPixelSize #6 
_rlnCtfMaxResolution #7 
_rlnCtfFigureOfMerit #8 
_rlnVoltage #9 
_rlnDefocusU #10 
_rlnDefocusV #11 
_rlnDefocusAngle #12 
_rlnSphericalAberration #13 
_rlnCtfBfactor #14 
_rlnCtfScalefactor #15 
_rlnPhaseShift #16 
_rlnAmplitudeContrast #17 
```

I have the suspicion the error is in the absence of `_rlnImageName`, although I'm not sure.

I've played around with `--copy-micrograph-coordinates`, and with `--passthrough`, although some of the online help forums were a couple of years old, so I'm not sure if all of these are still valid.

I feel like all the information is in the .star file, as all I really want are the locations, but now I need relion to properly read them as particles, instead of micrographs.

cheers,
Maarten

**Comment by asarnow** [comment]
Just read the stickied post on the cryoSPARC forum.

csparc2star.py 1.cs 2.cs 3.cs out.star

The particle paths (rlnImageName) and the alignments, etc. are in the main
job particles .cs file. The passthrough has extra info like coordinates,
micrographs, CTF.
