### ISSUE TITLE
 Importing 2D from cryosparc 2.1.4 back to relion 3.1

### ISSUE THREAD

**Issue by Omid1985** [asarnow/pyem#41]
Dear Daniel,

I am having some issues importing results from 2D back into relion for further processing. 
I used to use this command in the past which I suppose is now obsolete:
 /data/CRYOSPARC/pyem/csparc2star.py --copy-micrograph-coordinates /data/XXX/Extract/job41/particles.star /data/CRYOSPARC/USERS/Omid/P1/J154/particles_selected.cs from_cryosparc.star

I now get the following error:
Traceback (most recent call last):
  File "/data/CRYOSPARC/pyem/csparc2star.py", line 28, in <module>
    from pyem import metadata
  File "/data/CRYOSPARC/pyem/pyem/__init__.py", line 3, in <module>
    from . import metadata
  File "/data/CRYOSPARC/pyem/pyem/metadata.py", line 401
    ptdf = util.dataframe_from_records_mapped(pt, {**general, **micrograph})

I have also updated conda and pyem. The particles were originally extracted in Relion. I removed the top part (data_optics section) as suggested in the forums in order to import it into cryosparc. Could that be part of the problem? I assume that pyem will re-import this info back from cryosparc. 

I saw your recent post (https://discuss.cryosparc.com/t/csparc2star-py-rlnmicrographname-error/3750/3) as well on this issue but it was not clear to me what the command should be to get around this problem or if this is the same problem at all. 

Best,
Omid

**Comment by asarnow** [comment]
Please run with `--loglevel debug` and post the whole output. Thanks!

**Comment by mdppdm** [comment]
I'm having the same or similar problem with a new pyem installation (ubuntu 18.04, using the miniconda installation method). Here is my output with --loglevel debug

csparc2star.py cryosparc_P14_J30_003_particles.cs cryosparc_P14_J30_003_particles.star --loglevel debug
Traceback (most recent call last):
  File "/srv/local/progs/pyem/csparc2star.py", line 28, in <module>
    from pyem import metadata
  File "/srv/local/progs/pyem/pyem/__init__.py", line 3, in <module>
    from . import metadata
  File "/srv/local/progs/pyem/pyem/metadata.py", line 401
    ptdf = util.dataframe_from_records_mapped(pt, {**general, **micrograph})
                                                    ^
SyntaxError: invalid syntax

Mike

**Comment by Omid1985** [comment]
Hi Danel, 

I reinstalled minconda3, and that seem to have solved the above issue (at least for me), but now I get an entirely different issue. Looks like a module is missing or not being accessed. 

Here is my output with --loglevel debug:

/data/CRYOSPARC/pyem/csparc2star.py --loglevel debug --copy-micrograph-coordinates /data/XXX/movies_raw/Sep06_collect/Extract/job41/particles.star /data/CRYOSPARC/USERS/Omid/P1/J154/particles_selected.cs from_cryosparc.star
Traceback (most recent call last):
  File "/data/CRYOSPARC/pyem/csparc2star.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Omid

**Comment by mdppdm** [comment]
Sorry to hijack again, but I also got this error on a CentOS workstation with a new pyem installation.

ModuleNotFoundError: No module named 'numpy'

Mike

**Comment by Omid1985** [comment]
Hi Again,

So re-installed pyem again which now seems to find the modules but I still get an error:

/data/CRYOSPARC/miniconda3/pyem/csparc2star.py --loglevel debug --copy-micrograph-coordinates /data/XXX/movies_raw/Sep06_collect/Extract/job41/particles.star /data/CRYOSPARC/USERS/Omid/P1/J154/particles_selected.cs from_cryosparc.star
Traceback (most recent call last):
  File "/data/CRYOSPARC/miniconda3/pyem/csparc2star.py", line 28, in <module>
    from pyem import metadata
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/__init__.py", line 3, in <module>
    from . import metadata
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/metadata.py", line 23, in <module>
    from . import star
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/star.py", line 28, in <module>
    from pyem.util import natsort_values
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/util/__init__.py", line 3, in <module>
    from .util import *
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/util/util.py", line 28, in <module>
    from .. import vop
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/vop/__init__.py", line 3, in <module>
    from .vop import *
  File "/data/CRYOSPARC/miniconda3/pyem/pyem/vop/vop.py", line 22, in <module>
    from pyfftw.interfaces.numpy_fft import rfftn
  File "/data/CRYOSPARC/miniconda3/lib/python3.7/site-packages/pyfftw/__init__.py", line 43, in <module>
    from . import interfaces
  File "/data/CRYOSPARC/miniconda3/lib/python3.7/site-packages/pyfftw/interfaces/__init__.py", line 237, in <module>
    from . import scipy_fftpack
  File "/data/CRYOSPARC/miniconda3/lib/python3.7/site-packages/pyfftw/interfaces/scipy_fftpack.py", line 65, in <module>
    from scipy.fftpack import (dct, idct, dst, idst, diff, tilbert, itilbert,
ImportError: cannot import name '_fftpack' from 'scipy.fftpack' (/data/CRYOSPARC/miniconda3/lib/python3.7/site-packages/scipy/fftpack/__init__.py)

Omid

**Comment by asarnow** [comment]
> Sorry to hijack again, but I also got this error on a CentOS workstation with a new pyem installation.
> 
> Mike

These are separate errors caused by using Python 2 (in the first case) and either not installing the dependencies, or not activating the conda environment.

**Comment by asarnow** [comment]
> So re-installed pyem again which now seems to find the modules but I still get an error:
> 
> Omid

It would appear that some of the dependencies weren't installed, or the conda environment is not active. Check `which python` and `conda env list` to make sure the environment is how you expect.

**Comment by mdppdm** [comment]
Worked with python 3. Thanks, Mike

**Comment by Omid1985** [comment]
Hi Daniel,

Still having issues... My python path and conda env looks fine to me:
which python
/data/CRYOSPARC/miniconda3/bin/python

conda env list
# conda environments:
#
base                  *  /data/CRYOSPARC/miniconda3
pyem                     /data/CRYOSPARC/miniconda3/envs/pyem

Any suggetions?

**Comment by Omid1985** [comment]
> Worked with python 3. Thanks, Mike
Hi Mike, how did you switch to python3?

**Comment by mdppdm** [comment]
Omid, if you are still getting the "No module name 'numpy'" error, try re-activating pyem
>conda activate pyem

I initially installed pyem as root and then switched to my user account to run csparc2star.py. My user account default python is 2.7.5+. After the pyem installation, root is defaulting to python 3.7.4 from the miniconda3 installation (i.e., miniconda3/bin/python). After logging out and back in, I have to reactivate pyem or I get the numpy module error.

**Comment by Omid1985** [comment]
Hi Mike,

Thanks for the reply and suggestion. I tried what you said but now I got a whole new error:
/data/CRYOSPARC/pyem/csparc2star.py  --copy-micrograph-coordinates /data/XXX/movies_raw/Sep06_collect/Extract/job41/particles.star /data/CRYOSPARC/USERS/Omid/P1/J154/particles_selected.cs from_cryosparc.star
Defocus values not found
Traceback (most recent call last):
  File "/data/CRYOSPARC/pyem/csparc2star.py", line 106, in <module>
    sys.exit(main(parser.parse_args()))
  File "/data/CRYOSPARC/pyem/csparc2star.py", line 62, in main
    glob(args.copy_micrograph_coordinates)), join="inner")
  File "/data/CRYOSPARC/miniconda3/envs/pyem/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 255, in concat
    sort=sort,
  File "/data/CRYOSPARC/miniconda3/envs/pyem/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

I tried reinstalling as root and that also didn't work. I am doing all the installation in the same account so I should have to log in and out. 

Omid

**Comment by Omid1985** [comment]
If I activate pyem again then I get the error above but if I activate miniconda I get the old import error which basically seems to not load the dependencies or environment correctly as Daniel suggested

Omid

**Comment by mdppdm** [comment]
No, you don't have to log out and back in. I was just making the point that if I do log out I have to re-activate pyem.

**Comment by Omid1985** [comment]
> No, you don't have to log out and back in. I was just making the point that if I do log out I have to re-activate pyem.

Ah okay. Good to know. Thanks :)
