### ISSUE TITLE
csparc2star.py trouble - still

### ISSUE THREAD

**Issue by ic1062** [asarnow/pyem#42]
Daniel, i'm sorry to bother you. I'm having trouble (again/still) with csparc2star.py. I followed your installation instructions (detailed below), but I'm getting an error when converting and exported set of particles. The particles were originally from relion.

Help will be appreciated. Michael

csparc2star.py P4_J176_particles_exported.cs P4_J176_particles_exported.star --loglevel debug
Detected CryoSPARC 2+ .cs file
Reading primary file
Collecting particle parameters from most likely classes
Columns must be same length as key
Traceback (most recent call last):
  File "/srv/local/progs/pyem-release/csparc2star.py", line 42, in main
    df = metadata.parse_cryosparc_2_cs(cs, passthroughs=args.input[1:], minphic=args.minphic, boxsize=args.boxsize, swapxy=args.swapxy)
  File "/srv/local/progs/pyem-release/pyem/metadata.py", line 390, in parse_cryosparc_2_cs
    df = cryosparc_2_cs_model_parameters(cs, df, minphic=minphic)
  File "/srv/local/progs/pyem-release/pyem/metadata.py", line 333, in cryosparc_2_cs_model_parameters
    [cs[names[c]][i] for i, c in enumerate(cls)]))
  File "/srv/local/progs/miniconda3/envs/pyem/lib/python3.7/site-packages/pandas/core/frame.py", line 2935, in __setitem__
    self._setitem_array(key, value)
  File "/srv/local/progs/miniconda3/envs/pyem/lib/python3.7/site-packages/pandas/core/frame.py", line 2961, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Required fields could not be mapped. Are you using the right input file(s)?

### Installation on Ubuntu 18.04
download pyem-release branch 

https://github.com/asarnow/pyem

unzip in /srv/local/progs

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh

You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /srv/local/progs/miniconda3
Do you wish the installer to initialize Miniconda3
by running conda init? [yes|no]
yes

log out > log in

unset PYTHONPATH

. /srv/local/progs/miniconda3/etc/profile.d/conda.sh
 
conda create -n pyem
 
 conda activate pyem
 
conda install numpy scipy matplotlib seaborn numba pandas natsort

conda install -c conda-forge pyfftw healpy pathos

unzip pyem-release

cd pyem-release

pip install --no-dependencies -e .
  Obtaining file:///srv/local/progs/pyem-release
  Installing collected packages: pyem
  Running setup.py develop for pyem
  Successfully installed pyem

nano /etc/bash.bashrc
### pyem-release ###
PATH=:$PATH:/srv/local/progs/pyem-release

source /etc/bash.bashrc

csparc2star.py --help
usage: csparc2star.py [-h] [--boxsize BOXSIZE] [--class CLS]
                      [--minphic MINPHIC] [--stack-path STACK_PATH]
                      [--micrograph-path MICROGRAPH_PATH]
                      [--copy-micrograph-coordinates COPY_MICROGRAPH_COORDINATES]
                      [--swapxy] [--cached] [--transform TRANSFORM]
                      [--loglevel LOGLEVEL]
                      [input [input ...]] output

positional arguments:
  input                 Cryosparc metadata .csv (v0.6.5) or .cs (v2+) files
  output                Output .star file

optional arguments:
  -h, --help            show this help message and exit
  --boxsize BOXSIZE     Cryosparc refinement box size (if different from
                        particles)
  --class CLS           Keep this class in output, may be passed multiple
                        times
  --minphic MINPHIC     Minimum posterior probability for class assignment
  --stack-path STACK_PATH
                        Path to single particle stack
  --micrograph-path MICROGRAPH_PATH
                        Replacement path for micrographs
  --copy-micrograph-coordinates COPY_MICROGRAPH_COORDINATES
                        Source for micrograph paths and particle coordinates
                        (file or quoted glob)
  --swapxy              Swap X and Y axes when converting particle coordinates
  --cached              Keep paths from the Cryosparc 2+ cache when merging
                        coordinates
  --transform TRANSFORM
                        Apply rotation matrix or 3x4 rotation plus translation
                        matrix to particles (Numpy format)
  --loglevel LOGLEVEL, -l LOGLEVEL
                        Logging level and debug output

**Comment by asarnow** [comment]
Dupelicate of #59
