### ISSUE TITLE
3D refinement issue in Relion after exporting from cryosparc 

### ISSUE THREAD

**Issue by Jake4484** [asarnow/pyem#44]
Hi, 

 I ran into an issue recently that I was able to solve. I converted a selected 2D class from cryosparc to a star file using the c2sparc2star.py command. I then ran multiple 2D classifications and 3D classifications without any issues. Though during 3D auto refine,  I got a segment error. All of the _rlnRandomSubset column was set to 1 instead of a range of 1 and 2 values. By deleting the column, 3D auto refine worked fine. Is this something that occurs from a pyem conversion. I am using Relion 3.1.0-beta and the newest version of cryosparc. Here is a copy of the particle star file before I deleted the column:

# version 30001

data_optics

loop_ 
_rlnVoltage #1 
_rlnSphericalAberration #2 
_rlnAmplitudeContrast #3 
_rlnOpticsGroup #4 
_rlnImagePixelSize #5 
_rlnImageDimensionality #6 
_rlnImageSize #7 
  300.000000     2.700000     0.070000            1     1.060000            2          200 
 

# version 30001

data_particles

loop_ 
_rlnImageName #1 
_rlnMicrographName #2 
_rlnCoordinateX #3 
_rlnCoordinateY #4 
_rlnAnglePsi #5 
_rlnOriginXAngst #6 
_rlnOriginYAngst #7 
_rlnDefocusU #8 
_rlnDefocusV #9 
_rlnDefocusAngle #10 
_rlnPhaseShift #11 
_rlnCtfBfactor #12 
_rlnRandomSubset #13 
_rlnClassNumber #14 
_rlnOpticsGroup #15 
_rlnGroupNumber #16 
_rlnAngleRot #17 
_rlnAngleTilt #18 
_rlnNormCorrection #19 
_rlnLogLikeliContribution #20 
_rlnMaxValueProbDistribution #21 
_rlnNrOfSignificantSamples #22 
000014@J774/extract/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW.mrc  2334.000000  2788.000000    94.120187     5.421603     1.181603 29223.787109 28601.591797    25.456038     0.000000     0.000000            1            4            1            1     9.204747    89.815355     0.700938 17112.210941     0.274805          105 
000074@J774/extract/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW.mrc  3416.000000  2316.000000   145.879813     3.301603     4.361603 29223.787109 28601.591797    25.456038     0.000000     0.000000            1            4            1            1   -170.79525    90.184645     0.663777 16773.422483     0.340087           80 
000033@J774/extract/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW.mrc   665.000000  2217.000000     -6.38271     -8.35840     1.181603 29223.787109 28601.591797    25.456038     0.000000     0.000000            1            4            1            1    -30.24124    93.786117     0.673539 16900.963475     0.197940           39 
000161@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1090.000000  2175.000000    22.117371     -0.93840     -4.11840 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            4            1            2    -58.69878    96.867049     0.685048 16806.612919     0.400166           39 
000009@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc   433.000000   620.000000   -146.16819     9.661603     1.181603 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            4            1            2   -176.40750    85.390328     0.722245 16913.232501     0.242369           49 
000046@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1414.000000   248.000000    -12.50878     0.121603     7.541603 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            4            1            2    37.330451    27.313210     0.647260 16311.495712     0.620180           16 
000040@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  3362.000000  2151.000000   141.712664     1.181603     8.601602 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            4            1            2    -75.18663    90.818378     0.669095 16823.168263     0.197942           28 
000148@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  2697.000000  1555.000000   -110.20394     9.661603    11.781603 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            4            1            2   -163.22947    37.342240     0.693711 16715.405393     0.695409           16 
000112@J774/extract/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW.mrc  3385.000000  2779.000000    94.645874     6.481603     2.241603 26461.250000 26245.857422     0.341052     0.000000     0.000000            1            4            1            3    15.177866   114.005953     0.670025 16754.361465     0.753241           40 
000046@J774/extract/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW.mrc   672.000000   165.000000   -128.52164    14.961603     -6.23840 26461.250000 26245.857422     0.341052     0.000000     0.000000            1            4            1            3   150.669899   105.664212     0.696432 16769.565261     0.827122           20 
000030@J774/extract/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW.mrc  3331.000000  3019.000000    -75.03671     -7.29840     -1.99840 26461.250000 26245.857422     0.341052     0.000000     0.000000            1            4            1            3   140.361580   116.746192     0.670294 16866.984542     0.556135           35 
000020@J774/extract/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW.mrc   796.000000   529.000000    82.197054     0.121603    11.781603 26461.250000 26245.857422     0.341052     0.000000     0.000000            1            4            1            3    -51.38736    73.065729     0.671986 16825.010930     0.710078           28 
000009@J774/extract/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW.mrc  1376.000000  2771.000000     -0.30295     -6.23840     -4.11840 26461.250000 26245.857422     0.341052     0.000000     0.000000            1            4            1            3    -51.38736    73.065729     0.623831 16442.850967     0.858759           24 
000138@J774/extract/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204807_31204808_20190201_1935_aligned_DW.mrc  2922.000000  3623.000000   -106.14044     -3.05840     6.481603 26461.250000 26245.857422     0.341052     0.000000     0.000000            1            4            1            3    -84.77253    70.512775     0.659289 16795.785255     0.227446           65 
000011@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  1476.000000  3143.000000    -71.33932     -9.41840     -5.17840 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4     3.562630   114.080872     0.660083 16631.900281     0.761788            5 
000265@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc   997.000000  3350.000000    50.622266     -1.99840     -8.35840 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4    25.220518    64.303222     0.683167 16812.392686     0.284285           17 
000037@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  1345.000000   761.000000   164.964778     0.121603     4.361603 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4    -48.06638   107.306982     0.687698 16786.084987     0.299265            8 
000008@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc   672.000000   620.000000    -73.89048     2.241603     2.241603 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4    -29.80035    84.202158     0.664798 16753.889008     0.557087            9 
000175@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  2288.000000   877.000000    73.978363     2.241603     6.481602 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4   150.669899   105.664212     0.691363 16796.244649     0.636259           60 
000085@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  1237.000000   761.000000    -37.12173     -7.29840    -13.65840 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4    20.333782    22.008140     0.676979 16737.898359     0.440337            9 
000087@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  1886.000000  2705.000000   -151.90412     1.181603     -4.11840 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4   161.336217    95.362307     0.671897 16694.344017     0.399231           22 
000113@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc   394.000000  2928.000000   -169.12019    -10.47840    14.961603 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4   -170.79525    90.184645     0.693297 16645.338821     0.158388           23 
000012@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  2234.000000  3019.000000   178.095881     -5.17840     -4.11840 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4   161.336217    95.362307     0.672823 16829.892019     0.403285            6 
000287@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  2010.000000   860.000000     -1.62088     0.121603     5.421603 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4    -66.44722    55.694646     0.703808 16781.008687     0.406659           27 
000245@J774/extract/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204818_31204819_20190201_1932_aligned_DW.mrc  3115.000000  3466.000000   173.190312     7.541603     -3.05840 31429.634766 31092.513672    -33.23296     0.000000     0.000000            1            4            1            4   123.495382   112.458862     0.649564 16615.933570     0.457630           24 
000050@J774/extract/FoilHole_1159715_Data_31204825_31204826_20190201_1933_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204825_31204826_20190201_1933_aligned_DW.mrc  3038.000000  1208.000000   -165.46711     5.421603     2.241603 30977.580078 30530.318359    -66.56420     0.000000     0.000000            1            4            1            5    49.236360   102.894297     0.637815 16598.085598     0.348380           14 
000007@J774/extract/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW.mrc   332.000000  3433.000000    30.413799     1.181603     -0.93840 30219.453125 29600.865234    -64.16928     0.000000     0.000000            1            4            1            6    -40.94039    83.622055     0.696446 16951.494990     0.267894           14 
000004@J774/extract/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW.mrc  2891.000000  2936.000000   164.859986     5.421603     1.181603 30219.453125 29600.865234    -64.16928     0.000000     0.000000            1            4            1            6    -45.49771    68.286185     0.668709 16844.960660     0.247165           32 
000122@J774/extract/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW.mrc  1669.000000  2390.000000    -38.54981     -7.29840     -8.35840 30219.453125 29600.865234    -64.16928     0.000000     0.000000            1            4            1            6   149.307907    76.630152     0.674488 16948.558810     0.474562           35 
000049@J774/extract/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW.mrc   734.000000  2680.000000    88.298871     4.361603     5.421603 30219.453125 29600.865234    -64.16928     0.000000     0.000000            1            4            1            6    -38.93834    38.881156     0.696787 16919.660236     0.368154           15 
000113@J774/extract/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204833_31204834_20190201_1934_aligned_DW.mrc  1785.000000  3094.000000   -162.68707     6.481603     -1.99840 30219.453125 29600.865234    -64.16928     0.000000     0.000000            1            4            1            6    -12.97327    79.913974     0.657007 16727.464291     0.547840           11 
000008@J774/extract/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW.mrc  1615.000000  3284.000000     7.369394     2.241603    -12.59840 29487.628906 29163.509766    -71.80595     0.000000     0.000000            1            4            1            7    -52.73862    92.491214     0.713132 16674.150538     0.642377           19 
000062@J774/extract/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW.mrc  2211.000000  2895.000000    67.604065     -3.05840     -4.11840 29487.628906 29163.509766    -71.80595     0.000000     0.000000            1            4            1            7    -47.42354    97.629942     0.689446 16674.383150     0.749773           44 
000028@J774/extract/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW.mrc  1353.000000  1175.000000    85.321867    -14.71840    13.901603 29487.628906 29163.509766    -71.80595     0.000000     0.000000            1            4            1            7    70.852618    18.975993     0.692606 16769.116234     0.450483           60 
000127@J774/extract/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW.mrc   618.000000  2539.000000    -68.28734     -7.29840    -17.89840 29487.628906 29163.509766    -71.80595     0.000000     0.000000            1            4            1            7    -75.18663    90.818378     0.648401 16646.380029     0.228377           41 
000020@J774/extract/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204842_31204843_20190201_1936_aligned_DW.mrc   982.000000   819.000000   -120.84833     -1.99840     2.241603 29487.628906 29163.509766    -71.80595     0.000000     0.000000            1            4            1            7    -65.49940   111.100889     0.698358 16732.493381     0.542817           84 
000125@J774/extract/FoilHole_1159715_Data_31204854_31204855_20190201_1933_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204854_31204855_20190201_1933_aligned_DW.mrc   897.000000   405.000000   125.028314     2.241603     -1.99840 29240.873047 28953.306641    -84.93554     0.000000     0.000000            1            4            1            8    20.199164    79.960531     0.649479 16720.890494     0.366092           22 
000052@J774/extract/FoilHole_1159715_Data_31204854_31204855_20190201_1933_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204854_31204855_20190201_1933_aligned_DW.mrc   379.000000  1737.000000   144.991240     6.481603     -3.05840 29240.873047 28953.306641    -84.93554     0.000000     0.000000            1            4            1            8   -159.58553    90.344513     0.682161 16798.190565     0.294840           55 
000021@J774/extract/FoilHole_1159715_Data_31204854_31204855_20190201_1933_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204854_31204855_20190201_1933_aligned_DW.mrc   665.000000  1795.000000   174.810053    -11.53840     0.121603 29240.873047 28953.306641    -84.93554     0.000000     0.000000            1            4            1            8   -158.87860    60.947769     0.707236 16776.818391     0.158857           71 

Thanks! 

Jake

**Comment by asarnow** [comment]
The current version of pyem supports general star file IO. Relion 3.1 files are created by default, use `--relion2`/`-r2` to get Relion <=3.0 compatible files. There is a caveat of a missing rlnImageSize field, for now users should address this issue themselves using a text editor.

**Comment by asarnow** [comment]
Random subset issue still open.

**Comment by asarnow** [comment]
Correct behavior is to drop rlnRandomSubset if the number of unique values is one.
