### ISSUE TITLE
Importing 2D from cryosparc 2.15.0 back to relion 3.1

### ISSUE THREAD

**Issue by biolifei** [asarnow/pyem#46]
Hi,
I tried to use the pyem package command of csparc2star.py to convert the .cs file of cryosparc into a relion 3.1 star file and didn’t work for me.

python csparc2star.py --copy-micrograph-coordinates particles.star particles_selected.cs PC2.star
Traceback (most recent call last):
  File "csparc2star.py", line 28, in <module>
    from pyem import metadata
  File "/home/greg/pyem/pyem/__init__.py", line 3, in <module>
    from . import metadata
  File "/home/greg/pyem/pyem/metadata.py", line 399
    ptdf = util.dataframe_from_records_mapped(pt, {**general, **micrograph})
                                                    ^
SyntaxError: invalid syntax

python --version
Python 2.7.15 :: Anaconda, Inc.
python -c 'import pandas; print pandas.__version__'
0.21.0
any idea about how to solve this problem ?

**Comment by asarnow** [comment]
You must use Python 3 as explained in the installation instructions. Python 2 has reached its end-of-life and is not supported.
