### ISSUE TITLE
star.py error

### ISSUE THREAD

**Issue by mwieczo** [asarnow/pyem#47]
Hi, I am trying to apply a 3x4 transformation matrix obtained from chimera on a particles.star file generated in relion 3.1, but am getting the following error:

(pyem) [kapoor@kapoor-linux1 n-1]$  star.py --transform '0.9 0.4 0.1 -121.1; -0.4 0.9 -0.1 139.7; -0.2 0.03 0.9 56.4' j206_particles_n-1_temp.star tt.star
/home/kapoor/pyem/pyem/star.py:531: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[UCSF.IMAGE_INDEX], df[UCSF.IMAGE_PATH] = \
/home/kapoor/pyem/pyem/star.py:539: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[UCSF.IMAGE_ORIGINAL_INDEX], df[UCSF.IMAGE_ORIGINAL_PATH] = \
Traceback (most recent call last):
  File "/home/kapoor/bin/star.py", line 360, in <module>
    sys.exit(main(parser.parse_args()))
  File "/home/kapoor/bin/star.py", line 129, in main
    r = np.array(json.loads(args.transform))
  File "/home/kapoor/miniconda3/envs/pyem/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/kapoor/miniconda3/envs/pyem/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Is my matrix input wrong? Any help would be much appreciated. Particle star file is pasted below (first few particles only as a test). 
Thanks,
MW

# version 30001

data_optics

loop_ 
_rlnOpticsGroupName #1 
_rlnOpticsGroup #2 
_rlnMtfFileName #3 
_rlnMicrographOriginalPixelSize #4 
_rlnVoltage #5 
_rlnSphericalAberration #6 
_rlnAmplitudeContrast #7 
_rlnImagePixelSize #8 
_rlnImageSize #9 
_rlnImageDimensionality #10 
_rlnMicrographPixelSize #11 
opticsGroup1            1 MTF_K2_200kV.star     5.200000   200.000000     2.700000     0.100000     5.200000          128            2     5.200000 
opticsGroup3            2 MTF_K2_200kV.star     5.200000   200.000000     2.700000     0.100000     5.200000          128            2     5.200000 
opticsGroup6            3 MTF_K2_200kV.star     5.200000   200.000000     2.700000     0.100000     5.200000          128            2     5.200000 
opticsGroup2            4 MTF_K2_300kV.star     5.200000   300.000000     2.700000     0.100000     5.200000          128            2     5.200000 
opticsGroup4            5 MTF_K2_300kV.star     5.200000   300.000000     2.700000     0.100000     5.200000          128            2     5.200000 
opticsGroup5            6 MTF_K2_300kV.star     5.200000   300.000000     2.700000     0.100000     5.200000          128            2     5.200000 
 

# version 30001

data_particles

loop_ 
_rlnCoordinateX #1 
_rlnCoordinateY #2 
_rlnAnglePsi #3 
_rlnImageName #4 
_rlnMicrographName #5 
_rlnOpticsGroup #6 
_rlnCtfMaxResolution #7 
_rlnCtfFigureOfMerit #8 
_rlnDefocusU #9 
_rlnDefocusV #10 
_rlnDefocusAngle #11 
_rlnCtfBfactor #12 
_rlnCtfScalefactor #13 
_rlnPhaseShift #14 
_rlnAngleRot #15 
_rlnAngleTilt #16 
_rlnOriginXAngst #17 
_rlnOriginYAngst #18 
_rlnClassNumber #19 
_rlnNormCorrection #20 
_rlnLogLikeliContribution #21 
_rlnMaxValueProbDistribution #22 
_rlnNrOfSignificantSamples #23 
_rlnGroupName #24 
_rlnRandomSubset #25 
_rlnGroupNumber #26 
  571.369000   982.462000   -115.51571 000014@Extract/job032/Micrographs_bin/20190430_Arctica_52A/grafix_0001_52A.mrcs Micrographs_bin/20190430_Arctica_52A/grafix_0001_52A.mrc            1    10.481889     0.068258 10853.190430  9793.325195    -36.83827     0.000000     1.000000     0.000000   127.483969    82.975249     -0.95396    10.946037            1     0.845320 43329.678841     0.090501           37   group_02            2            1 
  793.031000   509.877000    -14.26509 000023@Extract/job032/Micrographs_bin/20190430_Arctica_52A/grafix_0001_52A.mrcs Micrographs_bin/20190430_Arctica_52A/grafix_0001_52A.mrc            1    10.481889     0.068258 10853.190430  9793.325195    -36.83827     0.000000     1.000000     0.000000   131.749059    69.428113     7.946037     0.546037            1     0.885231 43202.085594     0.039006           58   group_02            1            1 
  332.554000   765.831000    -36.29312 000016@Extract/job032/Micrographs_bin/20190430_Arctica_52A/grafix_0003_52A.mrcs Micrographs_bin/20190430_Arctica_52A/grafix_0003_52A.mrc            1     9.716788     0.082300 14850.016602 14850.016602    49.183117     0.000000     1.000000     0.000000   -128.29879   131.967749     -0.95396     -2.45396            1     0.868942 44453.415240     0.075998           19   group_03            1            2 
  305.308000   719.492000   164.233498 000014@Extract/job032/Micrographs_bin/20190430_Arctica_52A/grafix_0003_52A.mrcs Micrographs_bin/20190430_Arctica_52A/grafix_0003_52A.mrc            1     9.716788     0.082300 14850.016602 14850.016602    49.183117     0.000000     1.000000     0.000000    -39.83175   108.013521    -18.75396     -8.35396            1     0.911413 44442.767064     0.088459           18   group_03            2            2 
  262.000000   112.846000   -175.25574 000004@Extract/job032/Micrographs_bin/20190430_Arctica_52A/grafix_0005_52A.mrcs Micrographs_bin/20190430_Arctica_52A/grafix_0005_52A.mrc            1     8.904347     0.091428 12476.629883 11975.007812    -73.42570     0.000000     1.000000     0.000000   -170.70390    48.441091    -16.55396    -11.35396            1     0.887011 43983.068081     0.098374           70   group_02            2            1

**Comment by asarnow** [comment]
The transformation matrix needs to be in the numpy / JSON format. In other
words:

'[[0.9, 0.4, 0.1], [-121.1, -0.4, 0.9,], [-0.1, 139.7, -0.2,], [0.03, 0.9,
56.4]]'

**Comment by mwieczo** [comment]
Works perfectly, thank you!
