### ISSUE TITLE
Converted star file using csparc2star.py cannot work in relion-3.1

### ISSUE THREAD

**Issue by sunny1226** [asarnow/pyem#48]
Hi Daniel, 
I have used pyem/0.5 csparc2star.py to converted a particle .cs file to a relion-3.1 star file. it works, however, the relion cannot use the star file to run classification. I have checked converted "_rlnImageName", and found the actual particle stack file is "xxxx.mrcs"; but star file records "xxxx.mrc". After I replaced all the .mrc to .mrcs in the star file, it works in relion-3.1. I guess that is a small bug.

**Comment by asarnow** [comment]
It's not a bug; the files are really called `.mrc` by cryoSPARC. Unfortunately, Relion insists on `.mrcs`. An easy workaround is explained in the [wiki](https://github.com/asarnow/pyem/wiki/Export-from-cryoSPARC-v2#relion-project).
