### ISSUE TITLE
csparc2star.py outputs invalid paths: "#@>path"

### ISSUE THREAD

**Issue by aaraun** [asarnow/pyem#50]
I exported a .cs file from a cryosparc v2 homo-refinment and converted to .star with csparc2star.py, but the output rlnImageName field isn't a valid path. The reason seems to be that the paths in the .cs file have a leading `>`, e.g. `>J01/extract/particles.mrc`, and it is not removed in the conversion to .star, yielding image names like `000001@>J01/extract/particles.mrc`. Removing the `>` with sed fixes this, but I figured I'd raise the issue anyway, just in case this is unexpected behaviour. (I don't know if a leading `>` is typical of the current cryosparc v2 version I'm using, or just an idiosyncrasy of my installation.)

**Comment by asarnow** [comment]
I'm not sure when/why it does that (certain symbolic links?). I'm not sure yet if I should do anything about it, since one often has to adjust the paths manually anyway.

**Comment by elmbeech** [comment]
I run this into the same issue, with cs files from cryosparc version v2.15.0+200710.
A detailed description can be found in this forum post: https://discuss.cryosparc.com/t/csparc2star-output-relion-compatibility/4978
