### ISSUE TITLE
csparc2star.py from passthrough .cs produces X-flipped and warped particle coordinates in RELION

### ISSUE THREAD

**Issue by basantab** [asarnow/pyem#52]
Hi Daniel,

Thank you for developing these very useful tools. I have been trying to import particle coordinates from csparc (2.15.0) to relion (3.1) using the very handy csparc2star.py, but have been running into the following issues:

1) The coordinates are flipped about the X-axis (not the diagonal, so I don't expect --swapxy to fix it).
2) The coordinates seem to be scaled by a small factor. When inspecting picks, one can tell that applying a small shift to center some particles will make other particles fall off center further. A small shift in addition to scaling cannot be discarded.

The X-axis flipping is easy to fix, but I can't tell what the correct scaling and/or shifting is, so perhaps it's worth figuring out why the coordinates are not being correctly parsed by csparc2star.py.

My current workflow:

The particles come from blob picking in csparc, (diameter 20 to 75A, max resolution to consider 4A), followed by curation, extraction in a 256pix box (0.57angpix, no scaling), 2D classification and 2D template selection.

I give csparc2star.py the passthrough_particles_selected.cs file from the 2D selection job, and get a star file with coordinates and micrograph paths (paths have to be edited to point at the relion-run motcor2 instead of the csparc inputs). Csparc and relion micrographs are the same dimensions (3710x3838).

I split the coordinates by micrograph name in different *.box-like files in order to import them to relion with the "Particle coordinates" node type. These particles, when extracted and inspected, are X-flipped and shifted/scaled by a small factor. This is further evidenced by the fact that 2D classification in RELION from these particles will yield mostly noise, when csparc produced clean classes.

Any idea where the issued could be coming from? Let me know if any additional information would be helpful. Your help is very much appreciated.

Thank you,
Benjamin

**Comment by basantab** [comment]
Hi Daniel,

Thank you for your reply. I now tried `--swapxy`, as per your suggestion, and that fixed the scaling problem. I was under the impression it would flip the image along the diagonal based on the description in the printed help from `csparc2star.py --help`.

I still had to flip the particle coordinates about the X axis (micrograph_y_size - y_coor_value). Maybe this is because when I ran motion correction in RELION I had to flip the gain upside down? Anyway, my problem is fixed.

Thank you again for your help!

**Comment by basantab** [comment]
Sorry, I think I spoke too soon, the particles are still off-center.

**Comment by asarnow** [comment]
I added `--invertx` and `--inverty` to the program to flip the axes. Some combination of these and `--swapxy` will work. If your particles are slightly off center, and not wildly mispicked, then it may simple be the picking quality. You can recenter with `star.py` or relion_particle_extract. Good luck!
