### ISSUE TITLE
csparc2star.py issue converting from .cs to .star

### ISSUE THREAD

**Issue by jianhaoc** [asarnow/pyem#53]
After performing "Select 2D" in cryosparc, I export the output and there are two files P9_J165_particles_selected_exported.cs and P9_J165_particles_selected_exported.csg.
I ran below command line to convert cryosparc data into relion format. There is a issue. 

$ csparc2star.py P9_J165_particles_selected_exported.cs P9_J165_particles_selected_exported.star
/home/z/sw/pyem/pyem/metadata.py:330: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=obj
ect' when creating the ndarray
  df[model[k]] = pd.DataFrame(np.array(
Columns must be same length as key
Traceback (most recent call last):
  File "/home/z/sw/pyem/csparc2star.py", line 42, in main
    df = metadata.parse_cryosparc_2_cs(cs, passthroughs=args.input[1:], minphic=args.minphic, boxsize=args.boxsize, swapxy=args.swapxy)
  File "/home/z/sw/pyem/pyem/metadata.py", line 398, in parse_cryosparc_2_cs
    df = cryosparc_2_cs_model_parameters(cs, df, minphic=minphic)
  File "/home/z/sw/pyem/pyem/metadata.py", line 330, in cryosparc_2_cs_model_parameters
    df[model[k]] = pd.DataFrame(np.array(
  File "/home/z/.conda/envs/pyem/lib/python3.8/site-packages/pandas/core/frame.py", line 3037, in __setitem__
    self._setitem_array(key, value)
  File "/home/z/.conda/envs/pyem/lib/python3.8/site-packages/pandas/core/frame.py", line 3063, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Required fields could not be mapped. Are you using the right input file(s)?

How can I  figure it out? Thank you!

**Comment by sunny1226** [comment]
Check NumPy and other requirements software version in python. When I install pyem with NumPy below 1.14, it will report such error. Hopefully, that might help.

**Comment by asarnow** [comment]
Closing in the absence of further communication. Please post again if there is an on-going issue.
