### ISSUE TITLE
pffttw not found

### ISSUE THREAD

**Issue by EB-kim** [asarnow/pyem#63]
Hi,
 I am trying to download pyem in anaconda environment. when I download the pyem, I get a packagenotfoundError: pffttw healpy. I also tried to download with pip install. Is there any other way that I can download the pffttw and healpy?

sincerely

Andy

**Comment by JeanMichelMoreau** [comment]
conda install -c conda-forge pyfftw healpy pathos

Add this line so you have the pyfftw, healpy and pathos packages

Jean-Michel

**Comment by EB-kim** [comment]
Thanks but I still didn't get healpy, I tried pip install and it failed to download.

**Comment by asarnow** [comment]
I think it's easier to follow the wiki instructions and get everything with conda. You should also be able to install healpy with pip, though. You might just need to double check which copy of python you are trying to use.
