### ISSUE TITLE
star2bild.py ValueError when using --sym

### ISSUE THREAD

**Issue by basantab** [asarnow/pyem#65]
Hi,

I'm experiencing the following error when I use the --sym option in star2bild.py:

```
(pyem)$ /nfs/home/star2bild.py --sym C2 --boxsize 256 new_assignments_fromClass1_10000Samp.star new_assignments_fromClass1_10000Samp.bild
/nfs/home/pyem/pyem/star.py:537: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[Relion.IMAGE_NAME].str.split("@").str
/nfs/home/pyem/pyem/star.py:545: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[Relion.IMAGE_ORIGINAL_NAME].str.split("@").str
Traceback (most recent call last):
  File "/nfs/home/pyem/star2bild.py", line 114, in <module>
    sys.exit(main(parser.parse_args()))
  File "/nfs/home/pyem/star2bild.py", line 43, in main
    args.sym = util.relion_symmetry_group(args.sym)
  File "/nfs/home/pyem/pyem/util/util.py", line 46, in relion_symmetry_group
    for i in range(1, len(lines), 4)]
  File "/nfs/home/pyem/pyem/util/util.py", line 46, in <listcomp>
    for i in range(1, len(lines), 4)]
  File "/nfs/home/pyem/pyem/util/util.py", line 45, in <listcomp>
    [[np.double(val) for val in l.split()] for l in lines[i:i + 3]])
  File "/nfs/home/pyem/pyem/util/util.py", line 45, in <listcomp>
    [[np.double(val) for val in l.split()] for l in lines[i:i + 3]])
ValueError: could not convert string to float: 'R(1)='
```

Everything works fine if I don't provide the symmetry with --sym, it even makes the right "half sphere" of distributions one would expect from a C2. Maybe the --sym option is not necessary in some cases?

Edited to remove user name.

Thank you for your help!
Benjamin

**Comment by asarnow** [comment]
Hi Benjamin,
The `--sym` option is only necessary if the refinement program doesn't limit the search space during symmetric refinements. I guess you are coming from Relion, so it's not needed. (On the other hand, cryoSPARC always searches the entire rotation sphere).

`star2bild.py` gets the symmetry operators from Relion, the output format changed slightly over time resulting in the bug.

**Comment by basantab** [comment]
That's very clear. Thank you Daniel!
