### ISSUE TITLE
Handle unaligned particles w/ Rodrigues vector (0, 0, 0)

### ISSUE THREAD

**Issue by fonsecareyna82** [asarnow/pyem#68]
When using **csparc2star.py** in order to convert a cs file to star file i'm getting this rows where there is missing a value and therefore two spaces appear together(e.g. first line, after 180.000000). 

I share the cs file:

https://mega.nz/file/teYljITB#bBjNexdaCGAdHwHqoQEa8FvU6oN0dVaaIBC8rjRHlUQ   

000001@J97/imported/mic_000002.mrcs 0.000000 180.000000  0.000000 0.000000 300.000000 10000.000000 0.814000 7502.899902 7341.939941 69.898994 2.000000 0.000000 0.100000 1 1
000002@J97/imported/mic_000002.mrcs 0.000000 180.000000  0.000000 0.000000 300.000000 10000.000000 0.814000 7502.899902 7341.939941 69.898994 2.000000 0.000000 0.100000 1 1
000003@J97/imported/mic_000002.mrcs 0.000000 180.000000  0.000000 0.000000 300.000000 10000.000000 0.814000 7502.899902 7341.939941 69.898994 2.000000 0.000000 0.100000 1 1
000004@J97/imported/mic_000002.mrcs 72.615349 66.549942 122.649124 0.250000 0.250000 300.000000 10000.000000 0.814000 7502.899902 7341.939941 69.898994 2.000000 0.000000 0.100000 1 1
000005@J97/imported/mic_000002.mrcs 135.620636 13.441959 45.620644 0.000000 0.000000 300.000000 10000.000000 0.814000 7502.899902 7341.939941 69.898994 2.000000 0.000000 0.100000 1 1

**Comment by fonsecareyna82** [comment]
Also, I want to comment that this .cs file is obtained from an ab_initio with an O symmetry

**Comment by pconesa** [comment]
We are seeing this when running ab initio with "non-recommended" symmetry...but the actually results are nice and time is much less. Got it today also with C4 symmetry. I guess that for some reason, CS does not assign matices to some particles?

**Comment by asarnow** [comment]
Thanks, I'll look into it. I have an inkling (particle probability thresholds)...

**Comment by pconesa** [comment]
Cool, we tried to trace it but code reached code we waren't capable of understand quickly. 

One more thing....how would you see, refactoring the structure a bit to make it a deployable pip package?

We might be able to help here.

**Comment by sunchang1990** [comment]
I encounter a similar issue recently: when a particle has a Rot/Tilt angle of 0/180, the Psi angle is not in the star file produced by pyem.

**Comment by pconesa** [comment]
Is this somewhere fixed?

For scipion, to use pyem we are installing a fix a commit. What would be the latest code to use?

**Comment by asarnow** [comment]
@pconesa It's not fixed yet, but I just determined it's caused by particles having their Rodrigues vector as (0, 0, 0). What should we do with these particles?

In regards to your previous message, I would greatly appreciate any help making pyem work as a pip or conda package.

**Comment by asarnow** [comment]
I am thinking the right thing to do is `np.any(np.isnan(eulers))` and then drop all of the alignments. There could also be a warning and keep only the particles with valid alignments.

**Comment by pconesa** [comment]
We see, CS comes with "nan" in rlnAngePSI. Is this something CS should fix? 

Only thing clear to me is that star file should be a valid start file. Not sure if those particles should reach the star file.?

**Comment by pconesa** [comment]
What about using the rlnEnabled field?

**Comment by asarnow** [comment]
That would be great if you have the time!

I agree the star file should be valid. Are the ab initio jobs with these particles definitely finished? I wonder if they have been aligned at all, or if they have a class probability that's very low, or another recognizable property. The easiest thing to do is to just drop all of the unaligned particles, but another possibility would be to add a small value (like 1e-16) to the alignments to prevent the resulting NaNs. (The rotation matrix is all NaNs, getting (0, 180, NaN) for the Euler angles instead of 3x NaN is because of some default values in my rot2euler function).

**Comment by asarnow** [comment]
Well, I fixed this finally by making the numba version of expmap() output an identity matrix in this case, just like the pure python version already did. I also wrote the code for using rlnEnabled, but I think it's most correct to set the identity rotation here.

Fix by 9ffd1624.

**Comment by pconesa** [comment]
Thanks!
