### ISSUE TITLE
csparc2star.py raises ValueError upon converting Downsample Particles job result

### ISSUE THREAD

**Issue by kttn8769** [asarnow/pyem#70]
Hi,

csparc2star.py raises `ValueError: Columns must be same length as key` upon converting a Downsample Particles job result.

Followings are the command and the input cs file used.
`csparc2star.py downsampled_particles.cs downsampled_particles.star
`

[downsampled_particles.zip](https://github.com/asarnow/pyem/files/7509221/downsampled_particles.zip)

The full error message is below

> /apps/PyEM/pyem/metadata.py:335: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
>   [cs[names[c]][i] for i, c in enumerate(cls)]))
> Columns must be same length as key
> Traceback (most recent call last):
>   File "/apps/PyEM/csparc2star.py", line 44, in main
>     invertx=args.invertx, inverty=args.inverty)
>   File "/apps/PyEM/pyem/metadata.py", line 415, in parse_cryosparc_2_cs
>     df = cryosparc_2_cs_model_parameters(cs, df, minphic=minphic)
>   File "/apps/PyEM/pyem/metadata.py", line 335, in cryosparc_2_cs_model_parameters
>     [cs[names[c]][i] for i, c in enumerate(cls)]))
>   File "/apps/pyenv/versions/anaconda3-5.3.1/envs/PyEM/lib/python3.7/site-packages/pandas/core/frame.py", line 3160, in __setitem__
>     self._setitem_array(key, value)
>   File "/apps/pyenv/versions/anaconda3-5.3.1/envs/PyEM/lib/python3.7/site-packages/pandas/core/frame.py", line 3189, in _setitem_array
>     raise ValueError("Columns must be same length as key")
> ValueError: Columns must be same length as key
> Required fields could not be mapped. Are you using the right input file(s)?

Thanks,
Kotaro

**Comment by kttn8769** [comment]
I found that there are both 'alignments2D/class_posterior' and 'alignments3D/class_posterior' in .cs files from Downsample Particles job.

And in the function metadata.cryosparc_2_cs_model_parmeters(), argmax operation between 2D class posterior and 3D class posterior was performed, which makes no sense.

**Comment by kttn8769** [comment]
Here is my workaround

kttn8769/pyem@fc5c0de6cebbec85df74686345319aca1b304cf0

**Comment by asarnow** [comment]
Thanks @kttn8769. I just pushed #4eb57bd which is similar but I think covers all the edge cases. Would you mind giving it a test to confirm?

**Comment by asarnow** [comment]
I thinks this is OK with the @kttn8769 's PR.
