### ISSUE TITLE
csparc2star.py raises KeyError: 'rlnImagePixelSize' with a cs from a hetero refine job

### ISSUE THREAD

**Issue by kttn8769** [asarnow/pyem#73]
Hi,

I encountered the `KeyError: 'rlnImagePixelSize'` error with the following condition.

* With the code of the commit 53c98e3
* Command: `csparc2star.py cryosparc_P1_J14_class_02_00062_particles.py cryosparc_P1_J14_class_02_00062_particles.star`
  * The cs file is from a heterogeneous refinement job type
  * I attached the zipped cs file.

The exception came from the below line.
https://github.com/asarnow/pyem/blob/53c98e3f3fb2caeaf318e4de9dd640e5ba521acf/pyem/star.py#L628

Below is the error message.
> Traceback (most recent call last):
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'rlnImagePixelSize'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/people/kttn/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
>     cli.main()
>   File "/usr/people/kttn/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
>     run()
>   File "/usr/people/kttn/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
>     runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/runpy.py", line 268, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/people/kttn/repos/pyem/csparc2star.py", line 120, in <module>
>     sys.exit(main(parser.parse_args()))
>   File "/usr/people/kttn/repos/pyem/csparc2star.py", line 81, in main
>     df = star.check_defaults(df, inplace=True)
>   File "/usr/people/kttn/repos/pyem/pyem/star.py", line 628, in check_defaults
>     df[it[0]] = df[it[1]] * df[Relion.IMAGEPIXELSIZE]
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/usr/people/kttn/.conda/envs/PyEM-debug/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> KeyError: 'rlnImagePixelSize'

[cryosparc_P1_J14_class_02_00062_particles.zip](https://github.com/asarnow/pyem/files/7546911/cryosparc_P1_J14_class_02_00062_particles.zip)

**Comment by asarnow** [comment]
Hi @kttn8769, you must give the passthrough file as well from that job, in order to copy important details like pixel size and CTF parameters.

Like this:
`csparc2star.py cryosparc_P1_J14_class_02_00062_particles.cs P1_J14_passthrough_particles.cs cryosparc_P1_J14_class_02_00062_particles.star`

Does it work?
