### ISSUE TITLE
`metadata.parse_fx_par()` check whether last two lines contains information before SKIP them

### ISSUE THREAD

**Issue by dongzhuoer** [asarnow/pyem#77]
https://github.com/asarnow/pyem/blob/7ea9851e6ded8a8e79b50365cf409115269aaaa6/pyem/metadata.py#L79

For some `.par` files, such as <http://ftp.ebi.ac.uk/empiar/world_availability/10076/data/Frealign9Parameter_0_r1.par>, the last two lines are almost identical to the third last line. If ignore them without checking, `par2star.py` would lose two particles in the resulting `.star` file

**Comment by asarnow** [comment]
The example file is a Frealign9 file, with most of the additional metadata data stripped out. `parse_fx_par()` is intended for FrealignX (cisTEM) files, which look sort of like this non-standard, minimal Frealign9 file, but actually have different headers. I think I found a compromise that works well for both FrealignX and minimal Frealign9 files.

Please give the current master a try and see if it's working for you.
