### ISSUE TITLE
Import error csparc2star.py

### ISSUE THREAD

**Issue by ghatzop** [asarnow/pyem#78]
I run the following command:
$ ./csparc2star.py /path/to/cryosparc/P55/J111/particles.cs from_csparc.star

Which returns the error:
```
Traceback (most recent call last):
  File "./csparc2star.py", line 28, in <module>
    from pyem import metadata
ImportError: cannot import name 'metadata' from 'pyem' /home/myusername/.local/lib/python3.7/site-packages/pyem/__init__.py)


$ which python
/opt/anaconda2/bin//python

$ python --version
Python 3.7.0
```

pyem installed through:
`$ pip install pyem 
`
Version of pyem is 2.1.0

Any suggestion on how to resolve this would be much appreciated.

**Comment by asarnow** [comment]
I've never uploaded pyem to the repository. You installed "PyEM," which is a project for controlling SerialEM.

Please follow the instructions in the wiki here, until we can finish implementing a conda package.
