### ISSUE TITLE
ImportError: No module named pandas

### ISSUE THREAD

**Issue by ic1062** [asarnow/pyem#8]
Hi and thanks for the script. I (attempted) to follow the installation instructions, but I'm get the "no module name pandas" error. Belwo is what I did. I will appreciate your help finding my error/problem. Thanks, Mike

$ which python 
/usr/bin/python
$ python --version
Python 2.7.6
$which pip
/usr/bin/pip

unzipped pyem-master.zip in /srv/local/progs
$cd pyem-master
$ sudo pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): seaborn in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pandas in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pathos in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six>=1.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.0 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): backports.functools-lru-cache in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): subprocess32 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): cycler>=0.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): ppft>=1.6.4.7 in /usr/local/lib/python2.7/dist-packages (from pathos->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): dill>=0.2.7 in /usr/local/lib/python2.7/dist-packages (from pathos->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): pox>=0.2.3 in /usr/local/lib/python2.7/dist-packages (from pathos->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): multiprocess>=0.70.5 in /usr/local/lib/python2.7/dist-packages (from pathos->-r requirements.txt (line 7))
Cleaning up...

$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/pyem-0.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/pyem-0.1.egg-info

$csparc2star.py cryosparc_exp000107_iter20_selected_from_000108.csv csparc-2D.star
Traceback (most recent call last):
  File "/srv/local/progs/pyem-master/csparc2star.py", line 25, in <module>
    import pandas as pd
ImportError: No module named pandas

**Comment by asarnow** [comment]
Hi,
My guess is that `/usr/bin/env python2.7` isn't the same one you installed
into, or that sudo is changing the environment in a way you don't expect.

Can you try `/usr/bin/env python2.7 -c "import sys; print sys.executable"`
and also `sudo python -c "import sys; print sys.executable"` ?

**Comment by asarnow** [comment]
Hi,
My guess is that `/usr/bin/env python2.7` isn't the same one you installed
into, or that sudo is changing the environment in a way you don't expect.

Can you try `/usr/bin/env python2.7 -c "import sys; print sys.executable"`
and also `sudo python -c "import sys; print sys.executable"` ?

**Comment by ic1062** [comment]
Solved - by hiding EMAN python
Thanks for the reply. I reinstalled pyem (with sudo) after hiding the EMAN 2.0 python, and your csparc2star.py works.

On another machine I have EMAN2.2. Can you suggest the best way to deal with multiple python installations, or should I remove the system python.
Thanks again.

**Comment by asarnow** [comment]
What I do is put the EMAN2.2/bin directory at the beginning of the PATH, so that it clobbers all the other pythons around. Then use the EMAN2.2 pip to install my code into EMAN2.2's python. The newer versions of numpy, etc. don't seem to cause any issues.

This is the method I describe in one of the wiki pages here.

**Comment by ic1062** [comment]
My EMAN2.2/bin is ahead of /usr/bin in my PATH, but 
$which pip 
/usr/bin/pip
$which python
/srv/local/progs/EMAN2/extlib/bin/python

**Comment by ic1062** [comment]
$pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by asarnow** [comment]
Do you edit `.bash_profile` or `.bashrc`? The profile is only refreshed if you log out all the way and back in. Also, for EMAN2 before 2.2, we set `PYTHONPATH` and `LD_LIBRARY_PATH` variables. For 2.2 those need to be unset. You could still have those in your profile/rc, or maybe your profile/rc are sourcing the setup script for old EMAN2. Another possibility is there is a file in /etc/profile.d/ or line in /etc/environment which are still added the old EMAN to your PATH.

**Comment by ic1062** [comment]
Good suggestions, and thanks again for the script - obviously it is a very useful tool.
