### ISSUE TITLE
Only one file at a time supported for CryoSPARC 0.6.5 .csv format”

### ISSUE THREAD

**Issue by udeepka** [asarnow/pyem#80]

**Comment by asarnow** [comment]
Caused by unquoted string passed to singularity wrapper on their local cluster.

**Comment by johnskal** [comment]
Hello!
I am trying to convert a homogeneous refinement job from cryosparc so I can perform particle polishing. I follow the instructions in the wiki (the easier way described first). Creating the motion corrected movies .star file fine, but creating the particle .star file does not work.

I get the same error mentioned in this thread, running this command:

csparc2star.py --inverty P62/J262/P62_J262_particles.csg P62/J262/P62_J262_passthrough_particles.cs Star/J262_particles.star

J262 points at the refinement job in cryosparc. My CS version is 3.3.2

**Comment by asarnow** [comment]
.csg is the wrong file, please try with the partiles.**cs** file. Also feel free to make new issues, if you comment on a closed one like this without reopening it it's hard for me to find.
