### ISSUE TITLE
Error converting a CS 3DClassification .cs file to .start

### ISSUE THREAD

**Issue by fonsecareyna82** [asarnow/pyem#83]
I have the same error when I run CS 3D class with more than 31 classes. With less than 32 classes, it converts .cs to .start just fine.
The error is the following:

 File "../pyem/metadata.py", line 420, in parse_cryosparc_2_cs
    df = cryosparc_2_cs_model_parameters(cs, df, minphic=minphic)
  File "../pyem/metadata.py", line 336, in cryosparc_2_cs_model_parameters
    cls_prob = np.choose(cls, phic)
  File "<__array_function__ internals>", line 5, in choose
  File "../lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 433, in choose
    return _wrapfunc(a, 'choose', choices, out=out, mode=mode)
  File "../lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: Need at least 0 and at most 32 array objects.

**Comment by asarnow** [comment]
This sounds fun! Can you please send me your .cs file via some file sharing service?

**Comment by fonsecareyna82** [comment]
Hi @asarnow, is very simple.....take any .cs file that has been generated by a 3D classification where more than 31 classes have been generated. This happens to me with any data set...I will share with  you 2 files. You should receive an email with the address of the folder where I have put them. Could you tell me what version of numpy do you use? Thank a lot.

**Comment by asarnow** [comment]
Thanks, I see the files but I think they are still encrypted, I can't download them. I haven't been targeting a particular numpy version, I would like it to work with any relatively recent one. I don't think I have any earlier than 1.18 on my computers.

**Comment by asarnow** [comment]
Fixed in 4af3869f, please give it a try!

**Comment by fonsecareyna82** [comment]
Thanks asarnow. I'll test this change and I'll tell you

**Comment by asarnow** [comment]
For my later reference.

https://stackoverflow.com/questions/39162235/alternative-for-numpy-choose-that-allows-an-arbitrary-or-at-least-more-than-32-a

**Comment by asarnow** [comment]
I think this is good, closing.
