### ISSUE TITLE
TypeError: parse_cryosparc_2_cs() got an unexpected keyword argument 'invertx'

### ISSUE THREAD

**Issue by ajcdurand** [asarnow/pyem#84]
I am getting this error message when trying to use csparc2star.py

Traceback (most recent call last):
  File "/mnt/storage/software/pyem/0.5/pyem/csparc2star.py", line 137, in <module>
    sys.exit(main(parser.parse_args()))
  File "/mnt/storage/software/pyem/0.5/pyem/csparc2star.py", line 46, in main
    df = metadata.parse_cryosparc_2_cs(cs, passthroughs=args.input[1:], minphic=args.minphic,
TypeError: parse_cryosparc_2_cs() got an unexpected keyword argument 'invertx'

How can we fix this?
Thanks

**Comment by ajcdurand** [comment]
We have try to reinstall it and it seems to work.

Thanks for your support.

**Comment by asarnow** [comment]
Great!
