### ISSUE TITLE
star2bild.py ValueError: unsupported format character ')' (0x29) at index 11

### ISSUE THREAD

**Issue by Henry-946** [asarnow/pyem#85]
Hi Daniel,

Thank you so much for coding such woderful package for our EM community! I encourntered an error when transfer the star file to bild to get the Euler angle distribution, pls see the output below:

star2bild.py cryosparc_P80_J652_004_particles_2.star cryosparc_P80_J652_004_particles_2.bild --boxsize 300
/replaced/1-install/pyem/pyem/star.py:539: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[UCSF.IMAGE_INDEX], df[UCSF.IMAGE_PATH] = \
/replaced/1-install/pyem/pyem/star.py:547: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[UCSF.IMAGE_ORIGINAL_INDEX], df[UCSF.IMAGE_ORIGINAL_PATH] = \
Traceback (most recent call last):
  File "/replaced/1-install/pyem/star2bild.py", line 122, in <module>
    sys.exit(main(parser.parse_args()))
  File "/replaced/1-install/pyem/star2bild.py", line 71, in main
    log.info("%.0f (%.2f%) +/- %.1f (%.2f%) particles per bin" %
ValueError: unsupported format character ')' (0x29) at index 11

I found the discussion about this in the cryosparc forum: https://discuss.cryosparc.com/t/visualizing-orientation-distribution-other-than-heatmap/2683/16
and you mentioned it was fixed already, I just reinstalled the pyem again, and got the same error, maybe there are something wrong with my operation~

Could you pls check this for me when you get a chance, many thanks!

Best,
Henry

**Comment by asarnow** [comment]
Just double checked, this is definitely fixed. Make sure you have the most recent version and also Python 3.

**Comment by asarnow** [comment]
If you followed the instructions, you should have the master branch checked out, which is always the most recent version. Are you sure you're actually using that copy when you run the commands? Is `which star.py` for example showing the right path?

**Comment by Henry-946** [comment]
Thanks a bunch, Daniel, for helping in troubleshooting!
I just updated my miniconda, removed and reinstalled pyem again with a
specific python=3.7.13, it works now~

Appreciate your help, Have a wonderful night!

Best,
Fengwei

Daniel Asarnow ***@***.***> 于2022年8月23日周二 22:00写道：

**Comment by asarnow** [comment]
Great, glad you got it running!

**Comment by Henry-946** [comment]
Many thanks for your kind assistance!
Have a wonderful day!

Best,
Fengwei

Daniel Asarnow ***@***.***> 于2022年8月24日周三 00:47写道：
