### ISSUE TITLE
star.py --merge-fields not working as expected.

### ISSUE THREAD

**Issue by mbelouso** [asarnow/pyem#91]
Hey there, 

Trying to get star.py to merge optics groups assignments from star files that only contain data_optics and data_micrographs loops, is it that star.py only works on files that look more like a particles.star file? Or is it that I'm doing something completely wrong?

Thanks mate!

See following example:
_File1.star_
data_micrographs

loop_ 
_rlnMicrographName #1 
_rlnOpticsGroup #2 
_rlnCtfImage #3 
_rlnDefocusU #4 
_rlnDefocusV #5 
_rlnCtfAstigmatism #6 
_rlnDefocusAngle #7 
_rlnCtfFigureOfMerit #8 
_rlnCtfMaxResolution #9 
MotionCorr/job002/Micrographs/FoilHole_7313473_Data_7311271_7311273_20220706_122658_EER.mrc            1 CtfFind/job003/Micrographs/FoilHole_7313473_Data_7311271_7311273_20220706_122658_EER_PS.ctf:mrc  8943.220703  8693.840820   249.379883    18.737141     0.268751     3.287557

_File2.star_
data_micrographs

loop_
_rlnMicrographMovieName #1 
_rlnOpticsGroup #2 
MotionCorr/job002/Micrographs/FoilHole_7313473_Data_7311271_7311273_20220706_122658_EER.mrc	36

_So when I run the command:_

`star.py --merge-field rlnOpticsGroup --merge-source File2.star File1.star mics_new.star`

_I get the following Error:_

Traceback (most recent call last):
  File "/home/mbelouso/pyem/star.py", line 376, in <module>
    sys.exit(main(parser.parse_args()))
  File "/home/mbelouso/pyem/star.py", line 240, in main
    df = star.smart_merge(df, merge_star, fields=args.merge_fields, key=args.merge_key, left_key=args.by_original)
  File "/home/mbelouso/pyem/pyem/star.py", line 185, in smart_merge
    s2 = s2.set_index(key, drop=False)
  File "/home/mbelouso/anaconda3/envs/pyem/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/mbelouso/anaconda3/envs/pyem/lib/python3.10/site-packages/pandas/core/frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: 'None of [None] are in the columns'

**Comment by asarnow** [comment]
There needs to a common field to use as the merge __key__. By default we check rlnImageName or other combinations of fields that can uniquely specify a particle in each file. I guess here you want to copy optics group IDs from a micrograph star file, correct? You can try setting the merge key to `--merge-key rlnMicrographName`. You'll have to edit the 2nd file to have that field instead of rlnMicrographMovieName. Looks like the paths do match so hopefully that's all you have to do.
